import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __dirname = dirname(fileURLToPath(import.meta.url));

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": ["warn", {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
      }],
      "react/display-name": "warn",
    },
  },
  {
    // scripts/ and scratchpad/ hold developer tooling (3cx debug probes,
    // one-off migrations, throwaway experiments) that never ships. Skip
    // lint on them so those files don't gate CI. next-env.d.ts is
    // auto-generated by Next.js and its triple-slash reference is
    // idiomatic — ignore that too.
    ignores: [
      ".next/**",
      "out/**",
      "build/**",
      "scripts/**",
      "scratchpad/**",
      "next-env.d.ts",
    ],
  },
];

export default eslintConfig;
