-- whole-app 01: enums (live)

CREATE TYPE public.address_type AS ENUM ('blue-plate', 'google-coords');
CREATE TYPE public.approval_source_type AS ENUM ('sale_order', 'order');
CREATE TYPE public.approval_status AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE public.approval_type AS ENUM ('margin', 'credit');
CREATE TYPE public.audit_severity AS ENUM ('info', 'warning', 'error', 'critical');
CREATE TYPE public.campaign_status AS ENUM ('active', 'scheduled', 'expired', 'disabled');
CREATE TYPE public.confirmation_status AS ENUM ('not_sent', 'sent', 'confirmed', 'no_response', 'manually_confirmed');
CREATE TYPE public.contract_status AS ENUM ('active', 'expiring_soon', 'overdue_payment', 'cancelled', 'completed', 'draft', 'manager_review', 'customer_pending', 'approved', 'rejected', 'expired');
CREATE TYPE public.contract_type AS ENUM ('preventive', 'area', 'general');
CREATE TYPE public.credit_debit_line_type AS ENUM ('original', 'returned');
CREATE TYPE public.credit_group_request_status AS ENUM ('pending', 'approved', 'rejected', 'cancelled');
CREATE TYPE public.credit_note_resolution_type AS ENUM ('refund', 'replacement', 'store_credit');
CREATE TYPE public.credit_note_status AS ENUM ('draft', 'approved', 'open', 'in_progress', 'resolved', 'void');
CREATE TYPE public.customer_entity_type AS ENUM ('individual', 'business');
CREATE TYPE public.division AS ENUM ('maintenance', 'cleaning', 'kitchen', 'pest-control');
CREATE TYPE public.employee_status AS ENUM ('active', 'vacation', 'archived', 'unassigned', 'on-task');
CREATE TYPE public.follow_up_request_status AS ENUM ('pending', 'confirmed', 'cancelled', 'rejected');
CREATE TYPE public.instruction_content_type AS ENUM ('text', 'pdf');
CREATE TYPE public.instruction_type AS ENUM ('pre-service', 'post-service');
CREATE TYPE public.inventory_check_event_type AS ENUM ('initialized', 'user_completed', 'all_counted', 'approval_action', 'approved', 'rejected', 'user_started', 'cancelled');
CREATE TYPE public.inventory_check_step_role AS ENUM ('accounting_manager', 'inventory_manager', 'responsible_person', 'brand_manager', 'owner');
CREATE TYPE public.inventory_type AS ENUM ('products', 'spare-parts', 'consumables', 'tools');
CREATE TYPE public.invoice_direction AS ENUM ('ar', 'ap');
CREATE TYPE public.invoice_doc_status AS ENUM ('draft', 'ready_to_send', 'sent', 'pending_approval', 'approved', 'rejected');
CREATE TYPE public.invoice_payment_status AS ENUM ('unpaid', 'partially_paid', 'paid', 'overdue');
CREATE TYPE public.invoice_source AS ENUM ('sale_order', 'contract', 'quotation');
CREATE TYPE public.invoice_status AS ENUM ('draft', 'sent', 'partially_paid', 'paid', 'overdue', 'cancelled', 'void');
CREATE TYPE public.invoice_type AS ENUM ('cash', 'credit');
CREATE TYPE public.message_source AS ENUM ('whatsapp', 'whatsapp_api', 'phone', 'sms', 'email', 'whatsapp_whapi', '3cx_call', 'manual');
CREATE TYPE public.notification_category AS ENUM ('order', 'contract', 'invoice', 'payment', 'system', 'reminder', 'booking');
CREATE TYPE public.notification_channel AS ENUM ('whatsapp', 'sms', 'email', 'push');
CREATE TYPE public.notification_status AS ENUM ('sent', 'failed', 'pending', 'delivered');
CREATE TYPE public.notification_trigger AS ENUM ('manual', 'scheduled', 'event', 'reminder');
CREATE TYPE public.order_quotation_status AS ENUM ('draft', 'sent', 'pending_approval', 'approved', 'customer_approved', 'rejected', 'expired', 'converted', 'cancelled');
CREATE TYPE public.order_status AS ENUM ('scheduled', 'confirmed', 'in-progress', 'completed', 'pending-approval', 'cancelled', 'waitlist', 'pending-confirmation', 'customer-unavailable');
CREATE TYPE public.payment_direction AS ENUM ('incoming', 'outgoing');
CREATE TYPE public.payment_source_type AS ENUM ('sale_order', 'purchase_order', 'invoice', 'bill');
CREATE TYPE public.payment_status AS ENUM ('completed', 'pending', 'failed', 'refunded', 'processing');
CREATE TYPE public.po_edit_request_status AS ENUM ('pending', 'approved', 'rejected', 'used');
CREATE TYPE public.po_stage AS ENUM ('rfq', 'draft', 'po');
CREATE TYPE public.po_status AS ENUM ('draft', 'pending_approval', 'approved', 'partially_received', 'received', 'completed', 'cancelled');
CREATE TYPE public.po_type AS ENUM ('rfq', 'draft', 'confirmed');
CREATE TYPE public.promotion_rule_type AS ENUM ('percentage', 'fixed', 'buy_one_get_one', 'buy_x_get_y', 'buy_x_discount_get_y');
CREATE TYPE public.qc_priority AS ENUM ('high', 'medium', 'low');
CREATE TYPE public.qc_schedule_status AS ENUM ('pending', 'in-progress', 'completed', 'missed');
CREATE TYPE public.receival_source_type AS ENUM ('purchase', 'inventory');
CREATE TYPE public.receival_status AS ENUM ('pending_approval', 'approved', 'rejected');
CREATE TYPE public.reminder_channel AS ENUM ('Email', 'SMS', 'WhatsApp');
CREATE TYPE public.return_source_type AS ENUM ('sale_order', 'purchase_order');
CREATE TYPE public.return_status AS ENUM ('pending', 'pending_inspection', 'received', 'restocked', 'closed', 'dispatched', 'supplier_confirmed', 'cancelled', 'resolved_credit', 'resolved_replacement', 'resolved_partial');
CREATE TYPE public.rfq_status AS ENUM ('draft', 'sent', 'received', 'cancelled');
CREATE TYPE public.sale_delivery_status AS ENUM ('pending', 'in_progress', 'delivered', 'cancelled');
CREATE TYPE public.sale_delivery_type AS ENUM ('standard', 'replacement');
CREATE TYPE public.sale_order_status AS ENUM ('quotation', 'confirmed', 'in_progress', 'delivered', 'cancelled', 'pending_approval', 'partial_delivery', 'invoiced', 'closed');
CREATE TYPE public.service_category AS ENUM ('Repair', 'Installation', 'Maintenance', 'Cleaning', 'Quick Service');
CREATE TYPE public.service_change_status AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE public.service_change_type AS ENUM ('add', 'edit', 'delete');
CREATE TYPE public.service_status AS ENUM ('active', 'inactive');
CREATE TYPE public.service_type AS ENUM ('standard', 'configurable');
CREATE TYPE public.shipment_mode AS ENUM ('air', 'sea', 'land', 'manual');
CREATE TYPE public.shipment_status AS ENUM ('booked', 'in_transit', 'customs', 'delivered', 'delayed');
CREATE TYPE public.stock_adjustment_type AS ENUM ('increase', 'decrease', 'set', 'damage', 'write_off');
CREATE TYPE public.stock_movement_type AS ENUM ('purchase_receival', 'sale_delivery', 'adjustment', 'transfer_in', 'transfer_out', 'cost_adjustment', 'receival_edit', 'free_receival', 'sale_return', 'sale_return_damaged', 'purchase_return', 'purchase_return_cancelled', 'inventory_check', 'inventory_receival_carve', 'inventory_receival_new', 'damaged_return_from_repair_as_good', 'consumption', 'transfer_shrinkage');
CREATE TYPE public.team_tag AS ENUM ('normal', 'emergency', 'qc', 'site-visit');
CREATE TYPE public.tl_order_type AS ENUM ('order', 'site-visit-single', 'site-visit-contract', 'contract', 'backwork', 'follow-up', 'qc');
CREATE TYPE public.tool_condition AS ENUM ('New', 'Good', 'Fair', 'Maintenance');
CREATE TYPE public.tool_lifecycle_type AS ENUM ('new', 'used', 'repaired');
CREATE TYPE public.tool_status AS ENUM ('available', 'assigned', 'maintenance', 'retired');
CREATE TYPE public.tool_tracking_mode AS ENUM ('serialized', 'bulk');
CREATE TYPE public.transfer_status AS ENUM ('pending', 'in_transit', 'pending_approval', 'approved', 'rejected', 'received', 'cancelled');
CREATE TYPE public.user_type AS ENUM ('internal', 'customer', 'employee', 'team-leader');
CREATE TYPE public.voucher_type AS ENUM ('single_use', 'multi_use', 'limited');
CREATE TYPE public.warranty_claim_status AS ENUM ('open', 'covered', 'rejected', 'in_progress', 'resolved', 'void');
CREATE TYPE public.warranty_source_type AS ENUM ('sale', 'service', 'contract');
