-- whole-app 03: indexes (non-constraint-backed, live post-repair)

CREATE INDEX idx_activity_log_entity ON public.activity_log USING btree (entity_type, entity_id);
CREATE INDEX idx_activity_log_module ON public.activity_log USING btree (module);
CREATE INDEX idx_approval_workflow_steps_archived_by ON public.approval_workflow_steps USING btree (archived_by);
CREATE INDEX idx_approval_workflow_steps_group_id ON public.approval_workflow_steps USING btree (group_id);
CREATE INDEX idx_approval_workflow_steps_role_id ON public.approval_workflow_steps USING btree (role_id);
CREATE INDEX bill_attachments_bill_id_idx ON public.bill_attachments USING btree (bill_id);
CREATE UNIQUE INDEX bill_attachments_storage_key_uniq ON public.bill_attachments USING btree (storage_key);
CREATE INDEX idx_bill_attachments_uploaded_by ON public.bill_attachments USING btree (uploaded_by);
CREATE INDEX idx_bill_line_items_bill_id ON public.bill_line_items USING btree (bill_id);
CREATE INDEX idx_bill_line_items_brand_variant_id ON public.bill_line_items USING btree (brand_variant_id);
CREATE INDEX idx_bills_division_id ON public.bills USING btree (division_id);
CREATE INDEX idx_bills_payment_status ON public.bills USING btree (payment_status) WHERE (payment_status <> 'paid'::invoice_payment_status);
CREATE INDEX idx_bills_purchase_order_id ON public.bills USING btree (purchase_order_id);
CREATE INDEX idx_bills_receival_id ON public.bills USING btree (receival_id);
CREATE INDEX idx_bills_supplier_id ON public.bills USING btree (supplier_id);
CREATE UNIQUE INDEX uq_brands_lower_name ON public.brands USING btree (lower(TRIM(BOTH FROM name)));
CREATE INDEX cogs_entries_code_idx ON public.cogs_entries USING btree (code) WHERE (code IS NOT NULL);
CREATE INDEX cogs_entries_discipline_idx ON public.cogs_entries USING btree (discipline_id) WHERE (discipline_id IS NOT NULL);
CREATE INDEX cogs_entries_milestone_idx ON public.cogs_entries USING btree (milestone_id) WHERE (milestone_id IS NOT NULL);
CREATE INDEX cogs_entries_source_id_idx ON public.cogs_entries USING btree (source_id);
CREATE INDEX idx_cogs_delivery ON public.cogs_entries USING btree (sale_delivery_id) WHERE (sale_delivery_id IS NOT NULL);
CREATE INDEX idx_cogs_entries_consumer_customer ON public.cogs_entries USING btree (consumer_customer_id);
CREATE INDEX idx_cogs_entries_consumer_division_id ON public.cogs_entries USING btree (consumer_division_id) WHERE (consumer_division_id IS NOT NULL);
CREATE INDEX idx_cogs_entries_consumer_sub ON public.cogs_entries USING btree (consumer_sub_container_id);
CREATE INDEX idx_cogs_entries_consumption ON public.cogs_entries USING btree (consumption_id) WHERE (consumption_id IS NOT NULL);
CREATE INDEX idx_cogs_entries_division_id ON public.cogs_entries USING btree (division_id) WHERE (division_id IS NOT NULL);
CREATE INDEX idx_cogs_entries_lc ON public.cogs_entries USING btree (landed_cost_id) WHERE (landed_cost_id IS NOT NULL);
CREATE INDEX idx_cogs_entries_sale_delivery_id ON public.cogs_entries USING btree (sale_delivery_id) WHERE (sale_delivery_id IS NOT NULL);
CREATE INDEX idx_cogs_entries_sale_order_id ON public.cogs_entries USING btree (sale_order_id) WHERE (sale_order_id IS NOT NULL);
CREATE INDEX idx_cogs_variant ON public.cogs_entries USING btree (brand_variant_id);
CREATE INDEX idx_cogs_variant_date ON public.cogs_entries USING btree (brand_variant_id, date);
CREATE INDEX idx_companies_created_by ON public.companies USING btree (created_by);
CREATE INDEX idx_companies_currency_id ON public.companies USING btree (currency_id);
CREATE INDEX idx_company_divisions_company_id ON public.company_divisions USING btree (company_id);
CREATE INDEX idx_company_divisions_created_by ON public.company_divisions USING btree (created_by);
CREATE INDEX idx_company_divisions_currency_id ON public.company_divisions USING btree (currency_id);
CREATE INDEX ce_edit_requests_consumption_idx ON public.consumption_edit_requests USING btree (consumption_id);
CREATE UNIQUE INDEX ce_edit_requests_one_pending_per_consumption ON public.consumption_edit_requests USING btree (consumption_id) WHERE (status = 'pending'::text);
CREATE INDEX ce_edit_requests_pending_idx ON public.consumption_edit_requests USING btree (consumption_id) WHERE (status = 'pending'::text);
CREATE INDEX idx_consumption_edit_requests_requested_by ON public.consumption_edit_requests USING btree (requested_by);
CREATE INDEX idx_consumption_edit_requests_reviewed_by ON public.consumption_edit_requests USING btree (reviewed_by);
CREATE INDEX idx_consumption_entries_cancelled_by ON public.consumption_entries USING btree (cancelled_by);
CREATE INDEX idx_consumption_entries_consumer_customer ON public.consumption_entries USING btree (consumer_customer_id) WHERE (consumer_customer_id IS NOT NULL);
CREATE INDEX idx_consumption_entries_consumer_sub ON public.consumption_entries USING btree (consumer_sub_container_id);
CREATE INDEX idx_consumption_entries_created_by ON public.consumption_entries USING btree (created_by);
CREATE INDEX idx_consumption_entries_discipline ON public.consumption_entries USING btree (discipline_id);
CREATE INDEX idx_consumption_entries_division ON public.consumption_entries USING btree (division_id) WHERE (division_id IS NOT NULL);
CREATE INDEX idx_consumption_entries_milestone ON public.consumption_entries USING btree (milestone_id);
CREATE INDEX idx_consumption_entries_posted_by ON public.consumption_entries USING btree (posted_by);
CREATE INDEX idx_consumption_entries_source_sub ON public.consumption_entries USING btree (source_sub_container_id);
CREATE INDEX idx_consumption_entries_source_warehouse ON public.consumption_entries USING btree (source_warehouse_id);
CREATE INDEX idx_consumption_entries_status_date ON public.consumption_entries USING btree (status, date DESC);
CREATE INDEX idx_consumption_lines_consumption ON public.consumption_lines USING btree (consumption_id);
CREATE INDEX idx_consumption_lines_variant ON public.consumption_lines USING btree (brand_variant_id);
CREATE INDEX idx_credit_group_payment_methods_payment_method_id ON public.credit_group_payment_methods USING btree (payment_method_id);
CREATE INDEX idx_credit_note_lines_invoice_line_id ON public.credit_note_lines USING btree (invoice_line_id);
CREATE INDEX idx_credit_note_lines_type ON public.credit_note_lines USING btree (credit_note_id, line_type);
CREATE INDEX idx_credit_notes_customer_id ON public.credit_notes USING btree (customer_id);
CREATE INDEX idx_credit_notes_invoice_id ON public.credit_notes USING btree (invoice_id);
CREATE INDEX idx_credit_notes_reason_id ON public.credit_notes USING btree (reason_id);
CREATE INDEX idx_credit_notes_refund_method_id ON public.credit_notes USING btree (refund_method_id);
CREATE INDEX idx_credit_notes_source_return_id ON public.credit_notes USING btree (source_return_id);
CREATE INDEX idx_custom_roles_created_by ON public.custom_roles USING btree (created_by);
CREATE INDEX ccga_pending_idx ON public.customer_credit_group_approvals USING btree (request_id) WHERE ((status = 'pending'::approval_status) AND is_active);
CREATE INDEX ccga_request_idx ON public.customer_credit_group_approvals USING btree (request_id);
CREATE INDEX idx_customer_credit_group_approvals_decided_by ON public.customer_credit_group_approvals USING btree (decided_by);
CREATE INDEX ccgr_customer_pending_idx ON public.customer_credit_group_requests USING btree (customer_id) WHERE (status = 'pending'::credit_group_request_status);
CREATE INDEX idx_customer_credit_group_requests_decided_by ON public.customer_credit_group_requests USING btree (decided_by);
CREATE INDEX idx_customer_credit_group_requests_previous_group_id ON public.customer_credit_group_requests USING btree (previous_group_id);
CREATE INDEX idx_customer_credit_group_requests_requested_by ON public.customer_credit_group_requests USING btree (requested_by);
CREATE INDEX idx_customer_credit_group_requests_requested_group_id ON public.customer_credit_group_requests USING btree (requested_group_id);
CREATE INDEX idx_customer_phones_customer ON public.customer_phones USING btree (customer_id);
CREATE INDEX idx_customer_phones_phone ON public.customer_phones USING btree (phone);
CREATE INDEX idx_customers_credit_group_id ON public.customers USING btree (credit_group_id);
CREATE INDEX idx_customers_name ON public.customers USING btree (name);
CREATE INDEX idx_debit_note_lines_note_id ON public.debit_note_lines USING btree (debit_note_id);
CREATE UNIQUE INDEX debit_notes_source_return_id_unique ON public.debit_notes USING btree (source_return_id) WHERE (source_return_id IS NOT NULL);
CREATE INDEX idx_debit_notes_bill_id ON public.debit_notes USING btree (bill_id);
CREATE INDEX idx_debit_notes_po_id ON public.debit_notes USING btree (purchase_order_id);
CREATE INDEX idx_debit_notes_reason_id ON public.debit_notes USING btree (reason_id);
CREATE INDEX idx_debit_notes_supplier_id ON public.debit_notes USING btree (supplier_id);
CREATE INDEX exchange_rate_change_log_document_idx ON public.exchange_rate_change_log USING btree (document_type, document_id, changed_at DESC);
CREATE INDEX idx_exchange_rate_change_log_changed_by ON public.exchange_rate_change_log USING btree (changed_by);
CREATE INDEX idx_fifo_brand ON public.fifo_cost_layers USING btree (brand_variant_id);
CREATE INDEX idx_fifo_cost_layers_receival ON public.fifo_cost_layers USING btree (receival_id);
CREATE INDEX idx_fifo_cost_layers_source ON public.fifo_cost_layers USING btree (source_type, source_id) WHERE (source_id IS NOT NULL);
CREATE INDEX idx_fifo_cost_layers_sub_container_id ON public.fifo_cost_layers USING btree (sub_container_id);
CREATE INDEX idx_fifo_cost_layers_warehouse_id ON public.fifo_cost_layers USING btree (warehouse_id);
CREATE INDEX idx_fifo_warehouse ON public.fifo_cost_layers USING btree (brand_variant_id, warehouse_id);
CREATE INDEX iad_category_idx ON public.inventory_attribute_definitions USING btree (category_id);
CREATE INDEX iad_key_idx ON public.inventory_attribute_definitions USING btree (attribute_key);
CREATE INDEX idx_inventory_attribute_definitions_created_by ON public.inventory_attribute_definitions USING btree (created_by);
CREATE INDEX iao_active_idx ON public.inventory_attribute_options USING btree (definition_id) WHERE (NOT is_archived);
CREATE INDEX iao_definition_idx ON public.inventory_attribute_options USING btree (definition_id);
CREATE UNIQUE INDEX iao_value_en_ci_uidx ON public.inventory_attribute_options USING btree (definition_id, lower(value_en));
CREATE INDEX idx_inventory_categories_default_sub_container ON public.inventory_categories USING btree (default_sub_container_id) WHERE (default_sub_container_id IS NOT NULL);
CREATE INDEX idx_inventory_categories_default_warranty_policy ON public.inventory_categories USING btree (default_warranty_policy_id) WHERE (default_warranty_policy_id IS NOT NULL);
CREATE INDEX idx_inventory_categories_parent_id ON public.inventory_categories USING btree (parent_id);
CREATE UNIQUE INDEX uq_inventory_categories_name_parent_type ON public.inventory_categories USING btree (type, parent_id, lower(TRIM(BOTH FROM name_en))) WHERE (parent_id IS NOT NULL);
CREATE UNIQUE INDEX uq_inventory_categories_name_root_type ON public.inventory_categories USING btree (type, lower(TRIM(BOTH FROM name_en))) WHERE (parent_id IS NULL);
CREATE INDEX idx_icd_division ON public.inventory_category_divisions USING btree (division_id);
CREATE INDEX idx_inventory_category_divisions_created_by ON public.inventory_category_divisions USING btree (created_by);
CREATE INDEX idx_inventory_check_approvals_check_id ON public.inventory_check_approvals USING btree (check_id);
CREATE INDEX idx_inventory_check_approvals_profile_id ON public.inventory_check_approvals USING btree (profile_id);
CREATE INDEX idx_inventory_check_assignments_check_id ON public.inventory_check_assignments USING btree (check_id, created_at);
CREATE INDEX idx_inventory_check_assignments_profile_id ON public.inventory_check_assignments USING btree (profile_id);
CREATE INDEX idx_inventory_check_items_assignment_id ON public.inventory_check_items USING btree (assignment_id);
CREATE INDEX idx_inventory_check_items_brand_variant_id ON public.inventory_check_items USING btree (brand_variant_id);
CREATE INDEX idx_inventory_check_items_check_id ON public.inventory_check_items USING btree (check_id);
CREATE INDEX idx_inventory_check_log_check_id ON public.inventory_check_log USING btree (check_id);
CREATE INDEX idx_inventory_check_log_profile_id ON public.inventory_check_log USING btree (profile_id);
CREATE INDEX idx_inventory_checks_created_at ON public.inventory_checks USING btree (created_at DESC);
CREATE INDEX idx_inventory_checks_initiated_by_profile_id ON public.inventory_checks USING btree (initiated_by_profile_id);
CREATE INDEX idx_inventory_checks_warehouse_id ON public.inventory_checks USING btree (warehouse_id);
CREATE INDEX ix_inventory_checks_sub_container ON public.inventory_checks USING btree (sub_container_id);
CREATE INDEX idx_idm_division ON public.inventory_damaged_movements USING btree (division_id);
CREATE INDEX idx_idm_source_disp ON public.inventory_damaged_movements USING btree (source_return_line_disposition_id);
CREATE INDEX idx_idm_source_transfer ON public.inventory_damaged_movements USING btree (source_transfer_id);
CREATE INDEX idx_idm_wh_variant_time ON public.inventory_damaged_movements USING btree (warehouse_id, brand_variant_id, created_at);
CREATE INDEX idx_inv_damaged_movements_brand_variant ON public.inventory_damaged_movements USING btree (brand_variant_id);
CREATE INDEX idx_inventory_damaged_movements_created_by ON public.inventory_damaged_movements USING btree (created_by);
CREATE INDEX idx_inv_damaged_stock_brand_variant ON public.inventory_damaged_stock USING btree (brand_variant_id);
CREATE INDEX idx_idsl_division ON public.inventory_damaged_stock_layers USING btree (division_id);
CREATE INDEX idx_idsl_wh_variant ON public.inventory_damaged_stock_layers USING btree (warehouse_id, brand_variant_id, layered_at);
CREATE INDEX idx_inv_damaged_stock_layers_brand_variant ON public.inventory_damaged_stock_layers USING btree (brand_variant_id);
CREATE INDEX idx_inventory_damaged_stock_layers_created_by ON public.inventory_damaged_stock_layers USING btree (created_by);
CREATE INDEX idx_inventory_damaged_stock_layers_source_return_line_id ON public.inventory_damaged_stock_layers USING btree (source_return_line_id);
CREATE INDEX idx_inventory_item_attributes_updated_by ON public.inventory_item_attributes USING btree (updated_by);
CREATE INDEX iia_definition_idx ON public.inventory_item_attributes USING btree (definition_id);
CREATE INDEX iia_item_idx ON public.inventory_item_attributes USING btree (item_id);
CREATE INDEX iia_option_idx ON public.inventory_item_attributes USING btree (option_id);
CREATE INDEX idx_brand_variants_item ON public.inventory_item_brand_variants USING btree (item_id);
CREATE INDEX idx_inventory_brand_variants_brand_id ON public.inventory_item_brand_variants USING btree (brand_id);
CREATE INDEX inventory_item_brand_variants_country_id_idx ON public.inventory_item_brand_variants USING btree (country_id);
CREATE UNIQUE INDEX uq_iibv_item_brand_origin ON public.inventory_item_brand_variants USING btree (item_id, brand_id, country_id) NULLS NOT DISTINCT;
CREATE INDEX idx_iid_category ON public.inventory_item_divisions USING btree (category_id) WHERE (category_id IS NOT NULL);
CREATE INDEX idx_iid_division ON public.inventory_item_divisions USING btree (division_id);
CREATE INDEX idx_inventory_item_divisions_created_by ON public.inventory_item_divisions USING btree (created_by);
CREATE INDEX idx_inventory_items_category ON public.inventory_items USING btree (category_id);
CREATE INDEX idx_inventory_items_default_sub_container_id ON public.inventory_items USING btree (default_sub_container_id) WHERE (default_sub_container_id IS NOT NULL);
CREATE INDEX idx_inventory_items_default_warehouse_id ON public.inventory_items USING btree (default_warehouse_id) WHERE (default_warehouse_id IS NOT NULL);
CREATE INDEX idx_inventory_items_sku ON public.inventory_items USING btree (sku);
CREATE INDEX idx_inventory_items_warranty_policy ON public.inventory_items USING btree (warranty_policy_id) WHERE (warranty_policy_id IS NOT NULL);
CREATE UNIQUE INDEX uq_inventory_items_name_category ON public.inventory_items USING btree (category_id, lower(TRIM(BOTH FROM name_en)));
CREATE INDEX idx_inv_stock_movements_sub_container_id ON public.inventory_stock_movements USING btree (sub_container_id);
CREATE INDEX idx_inv_stock_movements_warehouse_id ON public.inventory_stock_movements USING btree (warehouse_id);
CREATE INDEX idx_inventory_stock_movements_source_id ON public.inventory_stock_movements USING btree (source_id) WHERE (source_id IS NOT NULL);
CREATE INDEX idx_stock_mvmt_ref ON public.inventory_stock_movements USING btree (reference_type, reference_id);
CREATE INDEX idx_stock_mvmt_ref_id ON public.inventory_stock_movements USING btree (reference_id);
CREATE INDEX idx_stock_mvmt_variant ON public.inventory_stock_movements USING btree (brand_variant_id);
CREATE INDEX idx_invoice_line_items_brand_variant_id ON public.invoice_line_items USING btree (brand_variant_id);
CREATE INDEX idx_invoice_line_items_invoice ON public.invoice_line_items USING btree (invoice_id);
CREATE INDEX idx_landed_cost_item_alloc_brand_variant ON public.landed_cost_item_allocations USING btree (brand_variant_id);
CREATE INDEX idx_landed_cost_item_alloc_lc ON public.landed_cost_item_allocations USING btree (landed_cost_id);
CREATE INDEX idx_landed_cost_lines_currency_id ON public.landed_cost_lines USING btree (currency_id);
CREATE INDEX idx_landed_cost_lines_lc ON public.landed_cost_lines USING btree (landed_cost_id);
CREATE INDEX idx_landed_costs_currency_id ON public.landed_costs USING btree (currency_id);
CREATE INDEX idx_landed_costs_date ON public.landed_costs USING btree (date DESC);
CREATE INDEX idx_notifications_profile_pending ON public.notifications USING btree (profile_id, created_at DESC) WHERE (actioned_at IS NULL);
CREATE INDEX idx_notifications_profile_read ON public.notifications USING btree (profile_id, read_at);
CREATE INDEX idx_notifications_profile_unread_created ON public.notifications USING btree (profile_id, created_at DESC) WHERE (read_at IS NULL);
CREATE INDEX idx_notifications_related_id ON public.notifications USING btree (related_id);
CREATE INDEX idx_pba_bill ON public.payment_bill_allocations USING btree (bill_id);
CREATE INDEX idx_pba_payment ON public.payment_bill_allocations USING btree (payment_id);
CREATE INDEX idx_payment_installments_payment_id ON public.payment_installments USING btree (payment_id);
CREATE INDEX idx_payment_installments_plan_id ON public.payment_installments USING btree (plan_id);
CREATE INDEX idx_payment_plans_bill_id ON public.payment_plans USING btree (bill_id);
CREATE INDEX idx_payment_plans_invoice_id ON public.payment_plans USING btree (invoice_id);
CREATE INDEX idx_payments_bill_id ON public.payments USING btree (bill_id) WHERE (bill_id IS NOT NULL);
CREATE INDEX idx_payments_currency_id ON public.payments USING btree (currency_id);
CREATE INDEX idx_payments_customer_id ON public.payments USING btree (customer_id);
CREATE INDEX idx_payments_date ON public.payments USING btree (date);
CREATE INDEX idx_payments_incoming ON public.payments USING btree (direction, deleted_at) WHERE (direction = 'incoming'::payment_direction);
CREATE INDEX idx_payments_invoice ON public.payments USING btree (invoice_id);
CREATE INDEX idx_payments_method_id ON public.payments USING btree (method_id);
CREATE INDEX idx_payments_qb_synced ON public.payments USING btree (qb_synced) WHERE (qb_synced = false);
CREATE INDEX idx_payments_source ON public.payments USING btree (source_type, source_id);
CREATE INDEX idx_payments_status ON public.payments USING btree (status);
CREATE INDEX idx_payments_supplier_id ON public.payments USING btree (supplier_id);
CREATE INDEX payments_credit_note_id_idx ON public.payments USING btree (credit_note_id) WHERE (credit_note_id IS NOT NULL);
CREATE INDEX payments_debit_note_id_idx ON public.payments USING btree (debit_note_id) WHERE (debit_note_id IS NOT NULL);
CREATE INDEX idx_approval_chains_division ON public.po_approval_chains USING btree (division_id);
CREATE UNIQUE INDEX idx_approval_chains_single_global ON public.po_approval_chains USING btree ((true)) WHERE (division_id IS NULL);
CREATE INDEX idx_po_approvals_active_pending ON public.po_approvals USING btree (po_id, is_active, status);
CREATE INDEX idx_po_approvals_po_iteration ON public.po_approvals USING btree (po_id, iteration);
CREATE INDEX idx_po_edit_requests_requested_by ON public.po_edit_requests USING btree (requested_by);
CREATE INDEX idx_po_edit_requests_reviewed_by ON public.po_edit_requests USING btree (reviewed_by);
CREATE UNIQUE INDEX po_edit_requests_one_approved_per_po ON public.po_edit_requests USING btree (po_id) WHERE (status = 'approved'::po_edit_request_status);
CREATE INDEX po_edit_requests_pending_idx ON public.po_edit_requests USING btree (po_id) WHERE (status = 'pending'::po_edit_request_status);
CREATE INDEX po_edit_requests_po_idx ON public.po_edit_requests USING btree (po_id);
CREATE INDEX idx_po_line_items_brand_id ON public.po_line_items USING btree (brand_id) WHERE (brand_id IS NOT NULL);
CREATE INDEX idx_po_line_items_brand_variant ON public.po_line_items USING btree (brand_variant_id);
CREATE INDEX idx_po_line_items_po ON public.po_line_items USING btree (po_id);
CREATE INDEX po_line_items_division_id_idx ON public.po_line_items USING btree (division_id) WHERE (division_id IS NOT NULL);
CREATE INDEX idx_po_rfq_quote_items_po_line_item_id ON public.po_rfq_quote_items USING btree (po_line_item_id);
CREATE INDEX po_rfq_quote_items_quote_idx ON public.po_rfq_quote_items USING btree (quote_id);
CREATE INDEX idx_po_rfq_quotes_currency_id ON public.po_rfq_quotes USING btree (currency_id);
CREATE INDEX idx_po_rfq_quotes_supplier_id ON public.po_rfq_quotes USING btree (supplier_id);
CREATE INDEX po_rfq_quotes_po_idx ON public.po_rfq_quotes USING btree (po_id);
CREATE INDEX idx_po_version_lines_brand_variant ON public.po_version_lines USING btree (brand_variant_id);
CREATE INDEX idx_po_version_lines_version ON public.po_version_lines USING btree (po_version_id);
CREATE INDEX idx_po_versions_currency_id ON public.po_versions USING btree (currency_id);
CREATE INDEX idx_po_versions_submitted_by ON public.po_versions USING btree (submitted_by);
CREATE INDEX idx_po_versions_supplier ON public.po_versions USING btree (supplier_id);
CREATE INDEX po_versions_po_stage_idx ON public.po_versions USING btree (po_id, stage);
CREATE UNIQUE INDEX po_versions_po_stage_version_uidx ON public.po_versions USING btree (po_id, stage, version_number);
CREATE INDEX idx_project_disciplines_created_by ON public.project_disciplines USING btree (created_by);
CREATE INDEX idx_project_disciplines_discipline_id ON public.project_disciplines USING btree (discipline_id);
CREATE INDEX idx_project_milestones_created_by ON public.project_milestones USING btree (created_by);
CREATE INDEX idx_project_milestones_discipline_id ON public.project_milestones USING btree (discipline_id);
CREATE UNIQUE INDEX project_milestones_sub_disc_label_key ON public.project_milestones USING btree (sub_container_id, discipline_id, label);
CREATE INDEX idx_projects_created_by ON public.projects USING btree (created_by);
CREATE INDEX idx_projects_responsible_person_profile_id ON public.projects USING btree (responsible_person_profile_id);
CREATE INDEX idx_projects_warehouse_id ON public.projects USING btree (warehouse_id);
CREATE INDEX idx_po_status ON public.purchase_orders USING btree (status);
CREATE INDEX idx_purchase_orders_created_by ON public.purchase_orders USING btree (created_by);
CREATE INDEX idx_purchase_orders_currency_id ON public.purchase_orders USING btree (currency_id);
CREATE INDEX idx_purchase_orders_division_id ON public.purchase_orders USING btree (division_id);
CREATE INDEX idx_purchase_orders_initial_rate_captured_by ON public.purchase_orders USING btree (initial_rate_captured_by);
CREATE INDEX idx_purchase_orders_po_type ON public.purchase_orders USING btree (po_type);
CREATE INDEX idx_purchase_orders_supplier ON public.purchase_orders USING btree (supplier_id);
CREATE INDEX idx_purchase_orders_warehouse_id ON public.purchase_orders USING btree (warehouse_id);
CREATE INDEX purchase_orders_division_ids_gin ON public.purchase_orders USING gin (division_ids);
CREATE INDEX idx_reason_lists_created_by ON public.reason_lists USING btree (created_by);
CREATE INDEX idx_receival_edit_requests_approved_by ON public.receival_edit_requests USING btree (approved_by);
CREATE INDEX idx_receival_edit_requests_requested_by ON public.receival_edit_requests USING btree (requested_by);
CREATE INDEX idx_rer_receival ON public.receival_edit_requests USING btree (receival_id);
CREATE INDEX idx_rer_status ON public.receival_edit_requests USING btree (status);
CREATE INDEX idx_receival_items_brand_variant ON public.receival_items USING btree (brand_variant_id);
CREATE INDEX idx_receival_items_po_line_item ON public.receival_items USING btree (po_line_item_id);
CREATE INDEX idx_receival_items_receival_id ON public.receival_items USING btree (receival_id);
CREATE INDEX idx_receival_items_sub_container_id ON public.receival_items USING btree (sub_container_id);
CREATE INDEX idx_receivals_carved_from_layer_id ON public.receivals USING btree (carved_from_layer_id);
CREATE INDEX idx_receivals_division_id ON public.receivals USING btree (division_id) WHERE (division_id IS NOT NULL);
CREATE INDEX idx_receivals_po_id ON public.receivals USING btree (po_id);
CREATE INDEX idx_receivals_source_debit_note_id ON public.receivals USING btree (source_debit_note_id);
CREATE INDEX idx_receivals_warehouse_id ON public.receivals USING btree (warehouse_id);
CREATE INDEX idx_repair_vendors_created_by ON public.repair_vendors USING btree (created_by);
CREATE INDEX idx_repair_vendors_sub_container_id ON public.repair_vendors USING btree (sub_container_id);
CREATE INDEX idx_repair_vendors_virtual_warehouse_id ON public.repair_vendors USING btree (virtual_warehouse_id);
CREATE INDEX return_line_customer_resolutions_credit_note_id_idx ON public.return_line_customer_resolutions USING btree (credit_note_id) WHERE (credit_note_id IS NOT NULL);
CREATE INDEX return_line_customer_resolutions_return_line_id_idx ON public.return_line_customer_resolutions USING btree (return_line_id);
CREATE INDEX return_line_customer_resolutions_sale_delivery_id_idx ON public.return_line_customer_resolutions USING btree (sale_delivery_id) WHERE (sale_delivery_id IS NOT NULL);
CREATE INDEX return_line_inventory_dispositi_inventory_stock_movement_id_idx ON public.return_line_inventory_dispositions USING btree (inventory_stock_movement_id) WHERE (inventory_stock_movement_id IS NOT NULL);
CREATE INDEX return_line_inventory_dispositions_return_line_id_idx ON public.return_line_inventory_dispositions USING btree (return_line_id);
CREATE INDEX return_line_inventory_dispositions_warehouse_transfer_id_idx ON public.return_line_inventory_dispositions USING btree (warehouse_transfer_id) WHERE (warehouse_transfer_id IS NOT NULL);
CREATE INDEX idx_return_lines_brand_variant ON public.return_lines USING btree (brand_variant_id);
CREATE INDEX idx_return_lines_return ON public.return_lines USING btree (return_id);
CREATE INDEX return_lines_receival_item_id_idx ON public.return_lines USING btree (receival_item_id) WHERE (receival_item_id IS NOT NULL);
CREATE INDEX return_lines_sale_delivery_line_id_idx ON public.return_lines USING btree (sale_delivery_line_id) WHERE (sale_delivery_line_id IS NOT NULL);
CREATE INDEX idx_sale_deliveries_created_by ON public.sale_deliveries USING btree (created_by);
CREATE INDEX idx_sale_deliveries_credit_note_id ON public.sale_deliveries USING btree (source_credit_note_id) WHERE (source_credit_note_id IS NOT NULL);
CREATE INDEX idx_sale_deliveries_return_id ON public.sale_deliveries USING btree (return_id);
CREATE INDEX idx_sale_deliveries_sale_order_id ON public.sale_deliveries USING btree (sale_order_id);
CREATE INDEX idx_sale_deliveries_warehouse_id ON public.sale_deliveries USING btree (warehouse_id);
CREATE INDEX idx_sale_delivery_lines_brand_variant ON public.sale_delivery_lines USING btree (brand_variant_id);
CREATE INDEX idx_sale_delivery_lines_delivery ON public.sale_delivery_lines USING btree (sale_delivery_id);
CREATE INDEX approval_requests_pending_idx ON public.sale_order_approvals USING btree (source_id, approval_type, iteration) WHERE ((status = 'pending'::approval_status) AND (is_active = true));
CREATE INDEX approval_requests_source_idx ON public.sale_order_approvals USING btree (source_type, source_id, approval_type, iteration);
CREATE INDEX idx_sale_order_approvals_decided_by ON public.sale_order_approvals USING btree (decided_by);
CREATE INDEX idx_sale_order_approvals_requested_by ON public.sale_order_approvals USING btree (requested_by);
CREATE INDEX idx_sale_order_lines_brand_variant ON public.sale_order_lines USING btree (brand_variant_id);
CREATE INDEX idx_sale_order_lines_created_by ON public.sale_order_lines USING btree (created_by);
CREATE INDEX idx_sale_order_lines_sale_order ON public.sale_order_lines USING btree (sale_order_id);
CREATE INDEX idx_sale_orders_created_by ON public.sale_orders USING btree (created_by);
CREATE INDEX idx_sale_orders_currency_id ON public.sale_orders USING btree (currency_id);
CREATE INDEX idx_sale_orders_customer_id ON public.sale_orders USING btree (customer_id);
CREATE INDEX idx_sale_orders_division_id ON public.sale_orders USING btree (division_id);
CREATE INDEX idx_sale_orders_initial_rate_captured_by ON public.sale_orders USING btree (initial_rate_captured_by);
CREATE INDEX idx_shipments_po ON public.shipments USING btree (po_id);
CREATE INDEX idx_shipments_receival_id ON public.shipments USING btree (receival_id);
CREATE INDEX idx_shipments_status ON public.shipments USING btree (status);
CREATE INDEX idx_invoices_customer ON public.so_invoices USING btree (customer_id);
CREATE INDEX idx_invoices_division_id ON public.so_invoices USING btree (division_id);
CREATE INDEX idx_invoices_due_date ON public.so_invoices USING btree (due_date);
CREATE INDEX idx_invoices_qb_synced ON public.so_invoices USING btree (qb_synced) WHERE (qb_synced = false);
CREATE INDEX idx_invoices_sale_order_id ON public.so_invoices USING btree (sale_order_id);
CREATE INDEX idx_invoices_status ON public.so_invoices USING btree (status, payment_status);
CREATE INDEX idx_so_po_returns_created_by ON public.so_po_returns USING btree (created_by);
CREATE INDEX idx_so_po_returns_credit_note_id ON public.so_po_returns USING btree (credit_note_id);
CREATE INDEX idx_so_po_returns_division_id ON public.so_po_returns USING btree (division_id);
CREATE INDEX idx_so_po_returns_restock_warehouse_id ON public.so_po_returns USING btree (restock_warehouse_id);
CREATE INDEX idx_so_po_returns_warranty_claim ON public.so_po_returns USING btree (warranty_claim_id);
CREATE UNIQUE INDEX returns_return_number_unique ON public.so_po_returns USING btree (return_number) WHERE (deleted_at IS NULL);
CREATE INDEX so_po_returns_debit_note_id_idx ON public.so_po_returns USING btree (debit_note_id) WHERE (debit_note_id IS NOT NULL);
CREATE INDEX so_po_returns_source_delivery_id_idx ON public.so_po_returns USING btree (source_delivery_id);
CREATE INDEX idx_saa_adjustment ON public.stock_adjustment_approvals USING btree (adjustment_id);
CREATE INDEX idx_saa_pending ON public.stock_adjustment_approvals USING btree (adjustment_id, step_order) WHERE (status = 'pending'::text);
CREATE INDEX idx_stock_adjustment_approvals_profile_id ON public.stock_adjustment_approvals USING btree (profile_id);
CREATE INDEX idx_stock_adjustments_brand_variant_id ON public.stock_adjustments USING btree (brand_variant_id);
CREATE INDEX idx_stock_adjustments_created_at ON public.stock_adjustments USING btree (created_at DESC);
CREATE INDEX idx_stock_adjustments_requested_by ON public.stock_adjustments USING btree (requested_by);
CREATE INDEX idx_stock_adjustments_source_check_item_id ON public.stock_adjustments USING btree (source_check_item_id);
CREATE INDEX idx_stock_adjustments_source_pile ON public.stock_adjustments USING btree (source_pile) WHERE (source_pile = 'damaged'::text);
CREATE INDEX idx_stock_adjustments_sub_container_id ON public.stock_adjustments USING btree (sub_container_id);
CREATE INDEX idx_stock_adjustments_warehouse_id ON public.stock_adjustments USING btree (warehouse_id);
CREATE INDEX stock_adjustments_source_check_id_idx ON public.stock_adjustments USING btree (source_check_id) WHERE (source_check_id IS NOT NULL);
CREATE INDEX idx_suppliers_country_id ON public.suppliers USING btree (country_id);
CREATE INDEX idx_suppliers_created_by ON public.suppliers USING btree (created_by);
CREATE INDEX idx_suppliers_currency_id ON public.suppliers USING btree (currency_id);
CREATE INDEX suppliers_division_id_idx ON public.suppliers USING btree (division_id) WHERE (division_id IS NOT NULL);
CREATE INDEX idx_tool_asset_units_division ON public.tool_asset_units USING btree (division_id);
CREATE INDEX idx_tool_asset_units_item_placeholder ON public.tool_asset_units USING btree (item_id, is_placeholder) WHERE (is_placeholder = true);
CREATE INDEX idx_tool_asset_units_receival_item ON public.tool_asset_units USING btree (receival_item_id);
CREATE INDEX ix_tool_asset_units_current_team ON public.tool_asset_units USING btree (current_custody_location_id);
CREATE UNIQUE INDEX uq_tool_asset_units_item_serial ON public.tool_asset_units USING btree (item_id, serial_number) WHERE (serial_number IS NOT NULL);
CREATE INDEX ix_tool_check_sessions_division ON public.tool_check_sessions USING btree (division_id, status);
CREATE INDEX idx_tool_unit_assignments_returned_to_warehouse_id ON public.tool_unit_assignments USING btree (returned_to_warehouse_id);
CREATE INDEX ix_tool_unit_assignments_team ON public.tool_unit_assignments USING btree (custody_location_id);
CREATE INDEX ix_tool_unit_assignments_unit ON public.tool_unit_assignments USING btree (unit_id);
CREATE UNIQUE INDEX uq_tool_unit_open_assignment ON public.tool_unit_assignments USING btree (unit_id) WHERE (released_at IS NULL);
CREATE INDEX idx_tool_unit_inspections_custody_location_id ON public.tool_unit_inspections USING btree (custody_location_id);
CREATE INDEX ix_tool_unit_inspections_session ON public.tool_unit_inspections USING btree (session_id);
CREATE INDEX ix_tool_unit_inspections_unit ON public.tool_unit_inspections USING btree (unit_id, inspected_at DESC);
CREATE INDEX idx_user_company_divisions_created_by ON public.user_company_divisions USING btree (created_by);
CREATE INDEX idx_user_company_divisions_division_id ON public.user_company_divisions USING btree (division_id);
CREATE INDEX idx_user_divisions_profile_id ON public.user_company_divisions USING btree (profile_id);
CREATE INDEX idx_user_custom_roles_created_by ON public.user_custom_roles USING btree (created_by);
CREATE INDEX idx_user_custom_roles_role_id ON public.user_custom_roles USING btree (role_id);
CREATE INDEX idx_user_data_active_division_id ON public.user_data USING btree (active_division_id);
CREATE UNIQUE INDEX profiles_threecx_extension_uq ON public.user_data USING btree (threecx_extension) WHERE (threecx_extension IS NOT NULL);
CREATE INDEX idx_warehouse_item_requests_dest_sub_container_id ON public.warehouse_item_requests USING btree (dest_sub_container_id);
CREATE INDEX idx_warehouse_item_requests_requested_by ON public.warehouse_item_requests USING btree (requested_by);
CREATE INDEX idx_warehouse_item_requests_resolved_by ON public.warehouse_item_requests USING btree (resolved_by);
CREATE INDEX idx_wir_created_at ON public.warehouse_item_requests USING btree (created_at DESC);
CREATE INDEX idx_wir_request_group ON public.warehouse_item_requests USING btree (request_group_id) WHERE (request_group_id IS NOT NULL);
CREATE INDEX idx_wir_warehouse_status ON public.warehouse_item_requests USING btree (warehouse_id, status);
CREATE INDEX idx_warehouse_reorder_points_brand_variant_id ON public.warehouse_reorder_points USING btree (brand_variant_id);
CREATE INDEX idx_warehouse_responsible_persons_profile_id ON public.warehouse_responsible_persons USING btree (profile_id);
CREATE INDEX idx_warehouse_stock_allocations_brand_variant_id ON public.warehouse_stock_allocations USING btree (brand_variant_id);
CREATE INDEX idx_warehouse_stock_allocations_sub_container_id ON public.warehouse_stock_allocations USING btree (sub_container_id);
CREATE INDEX idx_wss_brand_variant ON public.warehouse_stock_summary USING btree (brand_variant_id);
CREATE INDEX idx_wss_sub_container ON public.warehouse_stock_summary USING btree (sub_container_id);
CREATE INDEX idx_warehouse_sub_containers_created_by ON public.warehouse_sub_containers USING btree (created_by);
CREATE INDEX idx_warehouse_sub_containers_discipline_id ON public.warehouse_sub_containers USING btree (discipline_id);
CREATE INDEX idx_wsc_division ON public.warehouse_sub_containers USING btree (division_id);
CREATE INDEX idx_wsc_responsible_person ON public.warehouse_sub_containers USING btree (responsible_person_profile_id) WHERE (responsible_person_profile_id IS NOT NULL);
CREATE INDEX idx_wsc_team_id ON public.warehouse_sub_containers USING btree (team_id) WHERE (team_id IS NOT NULL);
CREATE INDEX idx_wsc_warehouse ON public.warehouse_sub_containers USING btree (warehouse_id);
CREATE INDEX idx_wsc_wh_div ON public.warehouse_sub_containers USING btree (warehouse_id, division_id);
CREATE UNIQUE INDEX warehouse_sub_containers_project_discipline_uq ON public.warehouse_sub_containers USING btree (project_id, discipline_id) WHERE (project_id IS NOT NULL);
CREATE INDEX idx_warehouse_transfer_items_brand_variant ON public.warehouse_transfer_items USING btree (brand_variant_id);
CREATE INDEX idx_warehouse_transfer_items_sub_container_id ON public.warehouse_transfer_items USING btree (sub_container_id);
CREATE INDEX idx_warehouse_transfer_items_transfer ON public.warehouse_transfer_items USING btree (transfer_id);
CREATE INDEX idx_warehouse_transfers_approved_by_profile_id ON public.warehouse_transfers USING btree (approved_by_profile_id);
CREATE INDEX idx_warehouse_transfers_cancelled_by_profile_id ON public.warehouse_transfers USING btree (cancelled_by_profile_id);
CREATE INDEX idx_warehouse_transfers_created_at ON public.warehouse_transfers USING btree (created_at DESC);
CREATE INDEX idx_warehouse_transfers_created_by_profile_id ON public.warehouse_transfers USING btree (created_by_profile_id);
CREATE INDEX idx_warehouse_transfers_dispatched_by_profile_id ON public.warehouse_transfers USING btree (dispatched_by_profile_id);
CREATE INDEX idx_warehouse_transfers_from_sub_container_id ON public.warehouse_transfers USING btree (from_sub_container_id);
CREATE INDEX idx_warehouse_transfers_from_warehouse_id ON public.warehouse_transfers USING btree (from_warehouse_id);
CREATE INDEX idx_warehouse_transfers_received_by_profile_id ON public.warehouse_transfers USING btree (received_by_profile_id);
CREATE INDEX idx_warehouse_transfers_source_return_line_disposition_id ON public.warehouse_transfers USING btree (source_return_line_disposition_id);
CREATE INDEX idx_warehouse_transfers_to_sub_container_id ON public.warehouse_transfers USING btree (to_sub_container_id);
CREATE INDEX idx_warehouse_transfers_to_warehouse_id ON public.warehouse_transfers USING btree (to_warehouse_id);
CREATE INDEX idx_wt_repair_vendor ON public.warehouse_transfers USING btree (repair_vendor_id);
CREATE INDEX idx_wt_request_group ON public.warehouse_transfers USING btree (request_group_id) WHERE (request_group_id IS NOT NULL);
CREATE INDEX idx_wt_transfer_kind ON public.warehouse_transfers USING btree (transfer_kind);
CREATE INDEX ix_warehouse_transfers_tool_unit ON public.warehouse_transfers USING btree (tool_unit_id) WHERE (tool_unit_id IS NOT NULL);
CREATE INDEX idx_warehouses_company_id ON public.warehouses USING btree (company_id);
CREATE INDEX idx_warehouses_kind ON public.warehouses USING btree (warehouse_kind) WHERE (warehouse_kind <> 'general'::text);
CREATE INDEX idx_warehouses_repair_vendor_id ON public.warehouses USING btree (repair_vendor_id);
CREATE UNIQUE INDEX warehouses_one_project_wh ON public.warehouses USING btree (is_project_warehouse) WHERE is_project_warehouse;
CREATE INDEX idx_warranty_claims_decided_by ON public.warranty_claims USING btree (decided_by);
CREATE INDEX idx_warranty_claims_division ON public.warranty_claims USING btree (division_id);
CREATE INDEX idx_warranty_claims_linked_return_id ON public.warranty_claims USING btree (linked_return_id);
CREATE INDEX idx_warranty_claims_record ON public.warranty_claims USING btree (warranty_record_id);
CREATE INDEX idx_warranty_claims_reported_by ON public.warranty_claims USING btree (reported_by);
CREATE INDEX idx_warranty_claims_status ON public.warranty_claims USING btree (status);
CREATE INDEX idx_warranty_claims_voided_by ON public.warranty_claims USING btree (voided_by);
CREATE INDEX idx_warranty_number_counters_division_id ON public.warranty_number_counters USING btree (division_id);
CREATE INDEX idx_warranty_policies_created_by ON public.warranty_policies USING btree (created_by);
CREATE INDEX idx_warranty_records_brand_variant_id ON public.warranty_records USING btree (brand_variant_id);
CREATE INDEX idx_warranty_records_customer_end ON public.warranty_records USING btree (customer_id, end_date DESC);
CREATE INDEX idx_warranty_records_division ON public.warranty_records USING btree (division_id);
CREATE INDEX idx_warranty_records_end_date ON public.warranty_records USING btree (end_date);
CREATE INDEX idx_warranty_records_origin_country_id ON public.warranty_records USING btree (origin_country_id);
CREATE INDEX idx_warranty_records_policy ON public.warranty_records USING btree (policy_id);
CREATE INDEX idx_warranty_records_sale_order ON public.warranty_records USING btree (sale_order_id);
CREATE UNIQUE INDEX uq_warranty_records_consumption_line ON public.warranty_records USING btree (consumption_line_id);
