-- whole-app 05: triggers (live)

CREATE TRIGGER bill_line_items_cascade_pdf_invalidation AFTER INSERT OR DELETE OR UPDATE ON bill_line_items FOR EACH ROW EXECUTE FUNCTION bill_line_items_invalidate_parent_pdf_fn();
CREATE TRIGGER bills_invalidate_pdf_cache BEFORE UPDATE ON bills FOR EACH ROW EXECUTE FUNCTION bills_invalidate_pdf_cache_fn();
CREATE TRIGGER brands_propagate_name_trg AFTER UPDATE OF name ON brands FOR EACH ROW EXECUTE FUNCTION brands_propagate_name_fn();
CREATE TRIGGER set_brands_updated_at BEFORE UPDATE ON brands FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_cogs_entries_set_consumer_division BEFORE INSERT ON cogs_entries FOR EACH ROW EXECUTE FUNCTION set_consumer_division_from_sale_order();
CREATE TRIGGER trg_cogs_entries_set_division BEFORE INSERT ON cogs_entries FOR EACH ROW EXECUTE FUNCTION set_division_from_sale_order();
CREATE TRIGGER cleanup_company_assets_after_delete AFTER DELETE ON companies FOR EACH ROW EXECUTE FUNCTION trg_cleanup_company_assets_after_delete();
CREATE TRIGGER cleanup_company_assets_after_update AFTER UPDATE OF logo_url, stamp_url ON companies FOR EACH ROW EXECUTE FUNCTION trg_cleanup_company_assets_after_update();
CREATE TRIGGER sync_currency_id BEFORE INSERT OR UPDATE ON companies FOR EACH ROW EXECUTE FUNCTION _sync_currency_id_from_default_currency();
CREATE TRIGGER trg_companies_updated_at BEFORE UPDATE ON companies FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER cleanup_division_assets_after_delete AFTER DELETE ON company_divisions FOR EACH ROW EXECUTE FUNCTION trg_cleanup_division_assets_after_delete();
CREATE TRIGGER cleanup_division_assets_after_update AFTER UPDATE OF logo_url, stamp_url ON company_divisions FOR EACH ROW EXECUTE FUNCTION trg_cleanup_division_assets_after_update();
CREATE TRIGGER sync_currency_id BEFORE INSERT OR UPDATE ON company_divisions FOR EACH ROW EXECUTE FUNCTION _sync_currency_id_from_default_currency();
CREATE TRIGGER trg_divisions_updated_at BEFORE UPDATE ON company_divisions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_audit_consumption_edit_requests AFTER INSERT OR DELETE OR UPDATE ON consumption_edit_requests FOR EACH ROW EXECUTE FUNCTION log_activity_change('consumption', 'lean');
CREATE TRIGGER cleanup_consumption_attachments_after_delete AFTER DELETE ON consumption_entries FOR EACH ROW EXECUTE FUNCTION trg_cleanup_consumption_attachments_after_delete();
CREATE TRIGGER cleanup_consumption_attachments_after_update AFTER UPDATE OF attachments ON consumption_entries FOR EACH ROW EXECUTE FUNCTION trg_cleanup_consumption_attachments_after_update();
CREATE TRIGGER trg_audit_consumption_entries AFTER INSERT OR DELETE OR UPDATE ON consumption_entries FOR EACH ROW EXECUTE FUNCTION log_activity_change('consumption', 'full');
CREATE TRIGGER set_updated_at_credit_groups BEFORE UPDATE ON credit_groups FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER credit_notes_invalidate_pdf_cache BEFORE UPDATE ON credit_notes FOR EACH ROW EXECUTE FUNCTION credit_notes_invalidate_pdf_cache_fn();
CREATE TRIGGER sync_credit_note_reason_id BEFORE INSERT OR UPDATE ON credit_notes FOR EACH ROW EXECUTE FUNCTION _sync_credit_note_reason_id_fn();
CREATE TRIGGER sync_credit_note_refund_method_id BEFORE INSERT OR UPDATE ON credit_notes FOR EACH ROW EXECUTE FUNCTION _sync_credit_note_refund_method_id_fn();
CREATE TRIGGER trg_credit_notes_updated_at BEFORE UPDATE ON credit_notes FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_guard_credit_notes_immutable BEFORE UPDATE ON credit_notes FOR EACH ROW EXECUTE FUNCTION guard_credit_notes_immutable();
CREATE TRIGGER trg_currencies_updated_at BEFORE UPDATE ON currencies FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_custom_roles_updated_at BEFORE UPDATE ON custom_roles FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER cleanup_customer_credit_docs_after_delete AFTER DELETE ON customer_credit_docs FOR EACH ROW EXECUTE FUNCTION trg_cleanup_customer_credit_docs_after_delete();
CREATE TRIGGER cleanup_customer_credit_docs_after_update AFTER UPDATE OF cr_url, establishment_id_url, signed_credit_form_url ON customer_credit_docs FOR EACH ROW EXECUTE FUNCTION trg_cleanup_customer_credit_docs_after_update();
CREATE TRIGGER trg_ccgr_updated_at BEFORE UPDATE ON customer_credit_group_requests FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_guard_customer_credit_group BEFORE UPDATE ON customers FOR EACH ROW EXECUTE FUNCTION guard_customer_credit_group();
CREATE TRIGGER debit_notes_invalidate_pdf_cache BEFORE UPDATE ON debit_notes FOR EACH ROW EXECUTE FUNCTION debit_notes_invalidate_pdf_cache_fn();
CREATE TRIGGER sync_debit_note_reason_id BEFORE INSERT OR UPDATE ON debit_notes FOR EACH ROW EXECUTE FUNCTION _sync_debit_note_reason_id_fn();
CREATE TRIGGER trg_guard_debit_notes_money_columns BEFORE UPDATE ON debit_notes FOR EACH ROW EXECUTE FUNCTION guard_debit_notes_money_columns();
CREATE TRIGGER trg_create_tool_units_on_receival AFTER INSERT ON fifo_cost_layers FOR EACH ROW EXECUTE FUNCTION create_tool_units_on_receival_layer();
CREATE TRIGGER trg_fifo_stock_summary AFTER INSERT OR DELETE OR UPDATE ON fifo_cost_layers FOR EACH ROW EXECUTE FUNCTION trg_fifo_refresh_stock_summary();
CREATE TRIGGER trg_remove_tool_placeholders_on_layer_delete AFTER DELETE ON fifo_cost_layers FOR EACH ROW EXECUTE FUNCTION remove_tool_placeholders_on_layer_delete();
CREATE TRIGGER trg_warehouse_stats AFTER INSERT OR DELETE OR UPDATE ON fifo_cost_layers FOR EACH ROW EXECUTE FUNCTION fn_refresh_warehouse_stats();
CREATE TRIGGER iad_branch_unique_trg BEFORE INSERT OR UPDATE OF category_id, attribute_key ON inventory_attribute_definitions FOR EACH ROW EXECUTE FUNCTION _check_attribute_key_branch_unique();
CREATE TRIGGER iad_set_updated_at BEFORE UPDATE ON inventory_attribute_definitions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_updated_at_inventory_categories BEFORE UPDATE ON inventory_categories FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_guard_tool_tracking_mode_switch BEFORE UPDATE ON inventory_categories FOR EACH ROW EXECUTE FUNCTION guard_tool_tracking_mode_switch();
CREATE TRIGGER trg_audit_inventory_check_approvals AFTER INSERT OR DELETE OR UPDATE ON inventory_check_approvals FOR EACH ROW EXECUTE FUNCTION log_activity_change('inventory_checks', 'full');
CREATE TRIGGER set_inventory_check_assignments_updated_at BEFORE UPDATE ON inventory_check_assignments FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_inventory_check_items_updated_at BEFORE UPDATE ON inventory_check_items FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_inventory_checks_updated_at BEFORE UPDATE ON inventory_checks FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_audit_inventory_checks AFTER INSERT OR DELETE OR UPDATE ON inventory_checks FOR EACH ROW EXECUTE FUNCTION log_activity_change('inventory_checks', 'lean');
CREATE TRIGGER trg_audit_inventory_damaged_movements AFTER INSERT OR DELETE OR UPDATE ON inventory_damaged_movements FOR EACH ROW EXECUTE FUNCTION log_activity_change('damaged_stock', 'full');
CREATE TRIGGER trg_sync_brand_variant_damaged_qty AFTER INSERT OR DELETE OR UPDATE OF qty ON inventory_damaged_stock FOR EACH ROW EXECUTE FUNCTION _sync_brand_variant_damaged_qty();
CREATE TRIGGER iia_set_updated_at BEFORE UPDATE ON inventory_item_attributes FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER inventory_pricing_guard_trg BEFORE UPDATE ON inventory_item_brand_variants FOR EACH ROW EXECUTE FUNCTION inventory_pricing_guard_fn();
CREATE TRIGGER set_updated_at_inventory_item_brand_variants BEFORE UPDATE ON inventory_item_brand_variants FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_auto_brand_variant_sku BEFORE INSERT OR UPDATE ON inventory_item_brand_variants FOR EACH ROW EXECUTE FUNCTION generate_brand_variant_sku();
CREATE TRIGGER trg_sync_brand_variants_brand_text BEFORE INSERT OR UPDATE OF brand_id ON inventory_item_brand_variants FOR EACH ROW EXECUTE FUNCTION sync_brand_variant_brand_text();
CREATE TRIGGER cleanup_inventory_item_image_after_delete AFTER DELETE ON inventory_items FOR EACH ROW EXECUTE FUNCTION trg_cleanup_inventory_item_image_after_delete();
CREATE TRIGGER cleanup_inventory_item_image_after_update AFTER UPDATE OF image_url ON inventory_items FOR EACH ROW EXECUTE FUNCTION trg_cleanup_inventory_item_image_after_update();
CREATE TRIGGER set_updated_at_inventory_items BEFORE UPDATE ON inventory_items FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_low_stock_notify AFTER INSERT ON inventory_stock_movements FOR EACH ROW EXECUTE FUNCTION check_low_stock_and_notify();
CREATE TRIGGER invoice_line_items_cascade_pdf_invalidation AFTER INSERT OR DELETE OR UPDATE ON invoice_line_items FOR EACH ROW EXECUTE FUNCTION invoice_line_items_invalidate_parent_pdf_fn();
CREATE TRIGGER cleanup_landed_cost_bill_after_delete AFTER DELETE ON landed_cost_lines FOR EACH ROW EXECUTE FUNCTION trg_cleanup_landed_cost_bill_after_delete();
CREATE TRIGGER cleanup_landed_cost_bill_after_update AFTER UPDATE OF bill_path ON landed_cost_lines FOR EACH ROW EXECUTE FUNCTION trg_cleanup_landed_cost_bill_after_update();
CREATE TRIGGER sync_currency_id BEFORE INSERT OR UPDATE ON landed_cost_lines FOR EACH ROW EXECUTE FUNCTION _sync_currency_id_from_currency();
CREATE TRIGGER sync_currency_id BEFORE INSERT OR UPDATE ON landed_costs FOR EACH ROW EXECUTE FUNCTION _sync_currency_id_from_currency();
CREATE TRIGGER trg_landed_cost_block_void_after_apply BEFORE UPDATE ON landed_costs FOR EACH ROW WHEN (new.voided_at IS DISTINCT FROM old.voided_at) EXECUTE FUNCTION trg_fn_landed_cost_block_void_after_apply();
CREATE TRIGGER trg_landed_costs_block_void_after_apply BEFORE UPDATE ON landed_costs FOR EACH ROW EXECUTE FUNCTION _landed_costs_block_void_after_apply();
CREATE TRIGGER trg_set_lc_number BEFORE INSERT ON landed_costs FOR EACH ROW EXECUTE FUNCTION _set_lc_number();
CREATE TRIGGER payment_bill_allocations_recompute_trg AFTER INSERT OR DELETE OR UPDATE ON payment_bill_allocations FOR EACH ROW EXECUTE FUNCTION payment_bill_allocations_trigger_recompute_fn();
CREATE TRIGGER bill_recompute_paid_trg AFTER INSERT OR DELETE OR UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION payments_trigger_bill_recompute_fn();
CREATE TRIGGER payments_recalc_ar_status AFTER INSERT OR DELETE OR UPDATE OF amount, invoice_id, deleted_at ON payments FOR EACH ROW EXECUTE FUNCTION trg_recalc_ar_payment_status();
CREATE TRIGGER sync_currency_id BEFORE INSERT OR UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION _sync_currency_id_from_currency();
CREATE TRIGGER sync_payment_method_id BEFORE INSERT OR UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION _sync_payment_method_id_fn();
CREATE TRIGGER trg_guard_payments_money_columns BEFORE UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION guard_payments_money_columns();
CREATE TRIGGER trg_invoice_recompute_paid AFTER INSERT OR DELETE OR UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION invoice_recompute_paid_fn();
CREATE TRIGGER trg_payments_cap_invoice_paid BEFORE INSERT ON payments FOR EACH ROW EXECUTE FUNCTION _payments_cap_invoice_paid();
CREATE TRIGGER trg_payments_compute_fx BEFORE INSERT OR UPDATE OF amount, exchange_rate, currency, source_type, source_id ON payments FOR EACH ROW EXECUTE FUNCTION _trg_payments_compute_fx();
CREATE TRIGGER trg_payments_redirect_to_invoice BEFORE INSERT ON payments FOR EACH ROW EXECUTE FUNCTION payments_redirect_to_invoice_fn();
CREATE TRIGGER trg_payments_refresh_document_fx AFTER INSERT OR DELETE OR UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION _trg_payments_refresh_document_fx();
CREATE TRIGGER trg_payments_sync_invoice_id BEFORE INSERT OR UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION payments_sync_invoice_id_fn();
CREATE TRIGGER po_line_items_cascade_pdf_invalidation AFTER INSERT OR DELETE OR UPDATE ON po_line_items FOR EACH ROW EXECUTE FUNCTION po_line_items_invalidate_parent_pdf_fn();
CREATE TRIGGER po_recompute_division_ids AFTER INSERT OR DELETE OR UPDATE OF division_id ON po_line_items FOR EACH ROW EXECUTE FUNCTION trg_po_recompute_division_ids();
CREATE TRIGGER trg_po_line_items_incoming AFTER INSERT OR DELETE OR UPDATE ON po_line_items FOR EACH ROW EXECUTE FUNCTION trg_fn_po_line_items_incoming();
CREATE TRIGGER sync_currency_id BEFORE INSERT OR UPDATE ON po_rfq_quotes FOR EACH ROW EXECUTE FUNCTION _sync_currency_id_from_currency();
CREATE TRIGGER sync_currency_id BEFORE INSERT OR UPDATE ON po_versions FOR EACH ROW EXECUTE FUNCTION _sync_currency_id_from_currency();
CREATE TRIGGER trg_audit_project_disciplines AFTER INSERT OR DELETE OR UPDATE ON project_disciplines FOR EACH ROW EXECUTE FUNCTION log_activity_change('projects', 'lean');
CREATE TRIGGER trg_audit_project_milestones AFTER INSERT OR DELETE OR UPDATE ON project_milestones FOR EACH ROW EXECUTE FUNCTION log_activity_change('projects', 'lean');
CREATE TRIGGER trg_audit_projects AFTER INSERT OR DELETE OR UPDATE ON projects FOR EACH ROW EXECUTE FUNCTION log_activity_change('projects', 'lean');
CREATE TRIGGER purchase_orders_invalidate_pdf_cache BEFORE UPDATE ON purchase_orders FOR EACH ROW EXECUTE FUNCTION purchase_orders_invalidate_pdf_cache_fn();
CREATE TRIGGER sync_currency_id BEFORE INSERT OR UPDATE ON purchase_orders FOR EACH ROW EXECUTE FUNCTION _sync_currency_id_from_currency();
CREATE TRIGGER trg_guard_po_locked_columns BEFORE UPDATE ON purchase_orders FOR EACH ROW EXECUTE FUNCTION guard_po_locked_columns();
CREATE TRIGGER trg_guard_po_privileged_status BEFORE INSERT OR UPDATE ON purchase_orders FOR EACH ROW EXECUTE FUNCTION guard_po_privileged_status();
CREATE TRIGGER trg_purchase_orders_incoming AFTER UPDATE OF status ON purchase_orders FOR EACH ROW EXECUTE FUNCTION trg_fn_purchase_orders_incoming();
CREATE TRIGGER trg_reason_list_categories_no_orphan_delete BEFORE DELETE ON reason_list_categories FOR EACH ROW EXECUTE FUNCTION reason_list_categories_no_orphan_delete();
CREATE TRIGGER trg_reason_lists_category_must_exist BEFORE INSERT OR UPDATE OF category ON reason_lists FOR EACH ROW EXECUTE FUNCTION reason_lists_category_must_exist();
CREATE TRIGGER trg_reason_lists_updated_at BEFORE UPDATE ON reason_lists FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER receival_items_cascade_check_pdf_invalidation AFTER INSERT OR DELETE OR UPDATE ON receival_items FOR EACH ROW EXECUTE FUNCTION receival_items_invalidate_parent_pdf_fn();
CREATE TRIGGER receivals_invalidate_check_pdf BEFORE UPDATE ON receivals FOR EACH ROW EXECUTE FUNCTION receivals_invalidate_check_pdf_fn();
CREATE TRIGGER trg_repair_vendor_provision_warehouse BEFORE INSERT ON repair_vendors FOR EACH ROW EXECUTE FUNCTION _repair_vendor_provision_warehouse();
CREATE TRIGGER trg_return_lines_provenance BEFORE INSERT OR UPDATE OF receival_item_id, sale_delivery_line_id, return_id ON return_lines FOR EACH ROW EXECUTE FUNCTION _enforce_return_line_provenance();
CREATE TRIGGER set_updated_at_sale_deliveries BEFORE UPDATE ON sale_deliveries FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_guard_sale_delivery_status BEFORE INSERT OR UPDATE ON sale_deliveries FOR EACH ROW EXECUTE FUNCTION guard_sale_delivery_status();
CREATE TRIGGER trg_approval_requests_decided_at BEFORE UPDATE ON sale_order_approvals FOR EACH ROW EXECUTE FUNCTION set_approval_request_decided_at();
CREATE TRIGGER trg_approval_requests_updated_at BEFORE UPDATE ON sale_order_approvals FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_log_sales_approval_decision AFTER UPDATE ON sale_order_approvals FOR EACH ROW EXECUTE FUNCTION log_sales_approval_decision();
CREATE TRIGGER sale_order_lines_cascade_pdf_invalidation AFTER INSERT OR DELETE OR UPDATE ON sale_order_lines FOR EACH ROW EXECUTE FUNCTION sale_order_lines_invalidate_parent_pdf_fn();
CREATE TRIGGER trg_sol_reserved_qty AFTER INSERT OR DELETE OR UPDATE ON sale_order_lines FOR EACH ROW EXECUTE FUNCTION trg_fn_sol_reserved_qty();
CREATE TRIGGER sale_orders_invalidate_pdf_cache BEFORE UPDATE ON sale_orders FOR EACH ROW EXECUTE FUNCTION sale_orders_invalidate_pdf_cache_fn();
CREATE TRIGGER set_updated_at_sale_orders BEFORE UPDATE ON sale_orders FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER sync_currency_id BEFORE INSERT OR UPDATE ON sale_orders FOR EACH ROW EXECUTE FUNCTION _sync_currency_id_from_currency();
CREATE TRIGGER trg_guard_so_privileged_status BEFORE INSERT OR UPDATE ON sale_orders FOR EACH ROW EXECUTE FUNCTION guard_so_privileged_status();
CREATE TRIGGER trg_sale_orders_block_bypass_approval BEFORE UPDATE OF status ON sale_orders FOR EACH ROW EXECUTE FUNCTION _sale_orders_block_bypass_approval();
CREATE TRIGGER trg_sale_orders_block_cancel_with_deliveries BEFORE UPDATE OF status ON sale_orders FOR EACH ROW EXECUTE FUNCTION _sale_orders_block_cancel_with_deliveries();
CREATE TRIGGER trg_so_reserved_qty AFTER UPDATE OF status ON sale_orders FOR EACH ROW EXECUTE FUNCTION trg_fn_so_reserved_qty();
CREATE TRIGGER invoices_invalidate_pdf_cache BEFORE UPDATE ON so_invoices FOR EACH ROW EXECUTE FUNCTION invoices_invalidate_pdf_cache_fn();
CREATE TRIGGER trg_guard_so_invoice_amounts BEFORE UPDATE ON so_invoices FOR EACH ROW EXECUTE FUNCTION guard_so_invoice_amounts();
CREATE TRIGGER trg_guard_so_po_returns_rpc_timestamps BEFORE UPDATE ON so_po_returns FOR EACH ROW EXECUTE FUNCTION guard_so_po_returns_rpc_timestamps();
CREATE TRIGGER trg_returns_updated_at BEFORE UPDATE ON so_po_returns FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_sync_warranty_claim_from_return AFTER UPDATE ON so_po_returns FOR EACH ROW WHEN (new.warranty_claim_id IS NOT NULL) EXECUTE FUNCTION _sync_warranty_claim_from_return();
CREATE TRIGGER trg_audit_stock_adjustment_approvals AFTER INSERT OR DELETE OR UPDATE ON stock_adjustment_approvals FOR EACH ROW EXECUTE FUNCTION log_activity_change('adjustments', 'full');
CREATE TRIGGER cleanup_stock_adjustment_photos_after_delete AFTER DELETE ON stock_adjustments FOR EACH ROW EXECUTE FUNCTION trg_cleanup_stock_adjustment_photos_after_delete();
CREATE TRIGGER cleanup_stock_adjustment_photos_after_update AFTER UPDATE OF photo_urls ON stock_adjustments FOR EACH ROW EXECUTE FUNCTION trg_cleanup_stock_adjustment_photos_after_update();
CREATE TRIGGER set_stock_adjustments_updated_at BEFORE UPDATE ON stock_adjustments FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_audit_stock_adjustments AFTER INSERT OR DELETE OR UPDATE ON stock_adjustments FOR EACH ROW EXECUTE FUNCTION log_activity_change('adjustments', 'full');
CREATE TRIGGER sync_supplier_country_id BEFORE INSERT OR UPDATE ON suppliers FOR EACH ROW EXECUTE FUNCTION _sync_supplier_country_id_fn();
CREATE TRIGGER trg_suppliers_updated_at BEFORE UPDATE ON suppliers FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_audit_tool_asset_units AFTER INSERT OR DELETE OR UPDATE ON tool_asset_units FOR EACH ROW EXECUTE FUNCTION log_activity_change('tools_assets', 'lean');
CREATE TRIGGER trg_guard_tool_unit_division_write BEFORE UPDATE ON tool_asset_units FOR EACH ROW EXECUTE FUNCTION guard_tool_unit_division_write();
CREATE TRIGGER trg_audit_tool_check_sessions AFTER INSERT OR DELETE OR UPDATE ON tool_check_sessions FOR EACH ROW EXECUTE FUNCTION log_activity_change('tools_assets', 'lean');
CREATE TRIGGER trg_audit_tool_unit_assignments AFTER INSERT OR DELETE OR UPDATE ON tool_unit_assignments FOR EACH ROW EXECUTE FUNCTION log_activity_change('tools_assets', 'lean');
CREATE TRIGGER trg_audit_tool_unit_inspections AFTER INSERT OR DELETE OR UPDATE ON tool_unit_inspections FOR EACH ROW EXECUTE FUNCTION log_activity_change('tools_assets', 'lean');
CREATE TRIGGER trg_clear_active_on_division_removal AFTER DELETE ON user_company_divisions FOR EACH ROW EXECUTE FUNCTION _trg_clear_active_on_division_removal();
CREATE TRIGGER trg_profiles_updated_at BEFORE UPDATE ON user_data FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_alloc_stock_summary AFTER INSERT OR DELETE OR UPDATE ON warehouse_stock_allocations FOR EACH ROW EXECUTE FUNCTION trg_alloc_refresh_stock_summary();
CREATE TRIGGER trg_enforce_sub_container_division_rule BEFORE INSERT OR UPDATE OF division_id, warehouse_id ON warehouse_sub_containers FOR EACH ROW EXECUTE FUNCTION _enforce_sub_container_division_rule();
CREATE TRIGGER trg_audit_warehouse_transfers AFTER INSERT OR DELETE OR UPDATE ON warehouse_transfers FOR EACH ROW EXECUTE FUNCTION log_activity_change('transfers', 'full');
CREATE TRIGGER trg_single_project_warehouse BEFORE INSERT OR UPDATE OF is_project_warehouse ON warehouses FOR EACH ROW WHEN (new.is_project_warehouse) EXECUTE FUNCTION _enforce_single_project_warehouse();
CREATE TRIGGER trg_warranty_policies_updated_at BEFORE UPDATE ON warranty_policies FOR EACH ROW EXECUTE FUNCTION warranty_policies_set_updated_at();
