'use client'

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { createClient } from '@/lib/supabase/client'

/**
 * Admin setting: whether inventory item/variant codes are auto-generated.
 *
 * Default is **OFF** — codes are entered manually when adding a brand variant
 * (a blank code still auto-fills via the `generate_brand_variant_sku` trigger,
 * so nothing is ever left without a code). When **ON**, the manual field is
 * hidden and every code is generated by the system.
 *
 * Stored in app_settings under `inventory_auto_generate_codes` as
 * `{ enabled: boolean }`, mirroring OrderQuotationSettingsAdmin.
 */
const SETTING_KEY = 'inventory_auto_generate_codes'

export function useAutoGenerateCodes() {
  return useQuery<boolean>({
    queryKey: ['app_settings', SETTING_KEY],
    staleTime: 5 * 60 * 1000,
    queryFn: async () => {
      const supabase = createClient()
      const { data } = await supabase
        .from('app_settings')
        .select('value')
        .eq('key', SETTING_KEY)
        .maybeSingle()
      return Boolean((data?.value as { enabled?: boolean } | null)?.enabled) // absent → OFF
    },
  })
}

export function useUpdateAutoGenerateCodes() {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: async (enabled: boolean) => {
      const supabase = createClient()
      const { error } = await supabase
        .from('app_settings')
        .upsert({ key: SETTING_KEY, value: { enabled } }, { onConflict: 'key' })
      if (error) throw error
      return enabled
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['app_settings', SETTING_KEY] })
    },
  })
}
