// This file is auto-generated by: npx supabase gen types typescript
// Run Task 6 to regenerate with actual schema types
// eslint-disable-next-line @typescript-eslint/no-empty-interface
export type Database = {
  public: {
    Tables: Record<string, { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}

export type Tables<T extends string> = Database['public']['Tables'][T]['Row']
export type Enums<T extends string> = Database['public']['Enums'][T]
export type InsertTables<T extends string> = Database['public']['Tables'][T]['Insert']
export type UpdateTables<T extends string> = Database['public']['Tables'][T]['Update']
