-- Auto-generated by scripts/migrate/generate_service_inventory_links.py
-- DO NOT EDIT MANUALLY

BEGIN;

-- ============================================================
-- Part A: service_inventory supply links
-- ============================================================

-- Supply: Supply and Install [Split Type AC 1.5 Ton Hommer]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install [Split Type AC 1.5 Ton Hommer]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ii.name_en ILIKE '%1.5%'
  AND bv.brand ILIKE 'Hommer'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install [Split Type AC 2 Ton Hommer]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install [Split Type AC 2 Ton Hommer]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ii.name_en ILIKE '%2%'
  AND bv.brand ILIKE 'Hommer'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install [Split Type AC 2.5 Ton Hommer]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install [Split Type AC 2.5 Ton Hommer]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ii.name_en ILIKE '%2.5%'
  AND bv.brand ILIKE 'Hommer'
ON CONFLICT DO NOTHING;
-- SKIP: 5 Stage
-- SKIP: 7 Stage
-- SKIP: CCK Jumbo
-- SKIP: Alkauther
-- SKIP: CCK RO

-- Supply: Supply and Install [Split Type AC 1 Ton Hommer]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install [Split Type AC 1 Ton Hommer]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ii.name_en ILIKE '%1%'
  AND bv.brand ILIKE 'Hommer'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install [Split Type AC 1.5 Ton Frego]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install [Split Type AC 1.5 Ton Frego]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ii.name_en ILIKE '%1.5%'
  AND bv.brand ILIKE 'Frego'
ON CONFLICT DO NOTHING;
-- SKIP: Media Filter

-- Supply: Supply and Install[Window Type AC 1.5 Ton Inverter -R410A Midea]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Window Type AC 1.5 Ton Inverter -R410A Midea]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Window%'
  AND ic.name_en ILIKE '%Inverter%'
  AND ii.name_en ILIKE '%1.5%'
  AND bv.brand ILIKE 'Midea'
ON CONFLICT DO NOTHING;
-- SKIP: Supply and Install [Split Type Air Deflector]
-- SKIP: Supply and Install [Stand Type Air Deflector]
-- SKIP: Water Cooler Stand Installation

-- Supply: Supply and Install Alfacool (Rotary) [1.5 Ton]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install Alfacool (Rotary) [1.5 Ton]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Water Cooler%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%1.5%'
  AND bv.brand ILIKE 'Alfacool'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install Alfacool (Rotary) [2 Ton]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install Alfacool (Rotary) [2 Ton]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Water Cooler%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%2%'
  AND bv.brand ILIKE 'Alfacool'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install Alfacool (Rotary) [2.5 Ton]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install Alfacool (Rotary) [2.5 Ton]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Water Cooler%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%2.5%'
  AND bv.brand ILIKE 'Alfacool'
ON CONFLICT DO NOTHING;

-- Supply: Supply and install [1.5 Ton] [Hommer]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and install [1.5 Ton] [Hommer]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Water Cooler%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%1.5%'
  AND bv.brand ILIKE 'Hommer'
ON CONFLICT DO NOTHING;

-- Supply: Supply and install [2 Ton] [Hommer]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and install [2 Ton] [Hommer]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Water Cooler%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%2%'
  AND bv.brand ILIKE 'Hommer'
ON CONFLICT DO NOTHING;

-- Supply: Supply and install [3 Ton] [Hommer]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and install [3 Ton] [Hommer]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Water Cooler%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%3%'
  AND bv.brand ILIKE 'Hommer'
ON CONFLICT DO NOTHING;
-- SKIP: Alfapure 7 Stage

-- Supply: Supply and Install Alfacool (Piston) [1.5 Ton]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install Alfacool (Piston) [1.5 Ton]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Water Cooler%'
  AND ic.name_en ILIKE '%Piston%'
  AND ii.name_en ILIKE '%1.5%'
  AND bv.brand ILIKE 'Alfacool'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install Alfacool (Piston) [2 Ton]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install Alfacool (Piston) [2 Ton]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Water Cooler%'
  AND ic.name_en ILIKE '%Piston%'
  AND ii.name_en ILIKE '%2%'
  AND bv.brand ILIKE 'Alfacool'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install Alfacool (Piston) [2.5 Ton]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install Alfacool (Piston) [2.5 Ton]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Water Cooler%'
  AND ic.name_en ILIKE '%Piston%'
  AND ii.name_en ILIKE '%2.5%'
  AND bv.brand ILIKE 'Alfacool'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 1.5 Ton Rotary-R410A GREE]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 1.5 Ton Rotary-R410A GREE]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%1.5%'
  AND bv.brand ILIKE 'GREE'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 2.5 Ton Rotary-R410A GREE]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 2.5 Ton Rotary-R410A GREE]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%2.5%'
  AND bv.brand ILIKE 'GREE'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 2.0 Ton Rotary-R410A N&SYS]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 2.0 Ton Rotary-R410A N&SYS]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%2.0%'
  AND bv.brand ILIKE 'N&SYS'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 3.0 Ton Rotary-R410A ORYX]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 3.0 Ton Rotary-R410A ORYX]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%3.0%'
  AND bv.brand ILIKE 'ORYX'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 2.5 Ton Piston-R410A Fergo]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 2.5 Ton Piston-R410A Fergo]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Piston%'
  AND ii.name_en ILIKE '%2.5%'
  AND bv.brand ILIKE 'Fergo'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 2.0 Ton Piston-R410A Fergo]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 2.0 Ton Piston-R410A Fergo]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Piston%'
  AND ii.name_en ILIKE '%2.0%'
  AND bv.brand ILIKE 'Fergo'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 3.0 Ton Rotary-R410A Hisense]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 3.0 Ton Rotary-R410A Hisense]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%3.0%'
  AND bv.brand ILIKE 'Hisense'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 2.5 Ton Rotary-R410A Hisense]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 2.5 Ton Rotary-R410A Hisense]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%2.5%'
  AND bv.brand ILIKE 'Hisense'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 1.5 Ton Rotary-R410A Midea]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 1.5 Ton Rotary-R410A Midea]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%1.5%'
  AND bv.brand ILIKE 'Midea'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 2.0 Ton Piston-R410A Midea]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 2.0 Ton Piston-R410A Midea]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Piston%'
  AND ii.name_en ILIKE '%2.0%'
  AND bv.brand ILIKE 'Midea'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 1.7 Ton Piston-R410A GREE]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 1.7 Ton Piston-R410A GREE]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Piston%'
  AND ii.name_en ILIKE '%1.7%'
  AND bv.brand ILIKE 'GREE'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 2.5 Ton Piston-R410A GREE]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 2.5 Ton Piston-R410A GREE]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Piston%'
  AND ii.name_en ILIKE '%2.5%'
  AND bv.brand ILIKE 'GREE'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Window Type AC 2.0 Ton Inverter -R410A Midea]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Window Type AC 2.0 Ton Inverter -R410A Midea]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Window%'
  AND ic.name_en ILIKE '%Inverter%'
  AND ii.name_en ILIKE '%2.0%'
  AND bv.brand ILIKE 'Midea'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Window Type AC 2.0 Ton Piston -R410A GREE]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Window Type AC 2.0 Ton Piston -R410A GREE]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Window%'
  AND ic.name_en ILIKE '%Piston%'
  AND ii.name_en ILIKE '%2.0%'
  AND bv.brand ILIKE 'GREE'
ON CONFLICT DO NOTHING;
-- SKIP: Supply and Install [Linear Diffuser Air Deflector]
-- SKIP: Supply and Install [Square Diffuser Air Deflector]

-- Supply: Supply and install [80 Gallon] [Alfaheat]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and install [80 Gallon] [Alfaheat]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Water Heater%'
  AND ii.name_en ILIKE '%80 Gallon%'
  AND bv.brand ILIKE 'Alfaheat'
ON CONFLICT DO NOTHING;

-- Supply: Supply and install [80 Gallon] [Bradford White]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and install [80 Gallon] [Bradford White]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Water Heater%'
  AND ii.name_en ILIKE '%80 Gallon%'
  AND bv.brand ILIKE 'Bradford White'
ON CONFLICT DO NOTHING;

-- Supply: Supply and install [80 Gallon] [American Water Heater]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and install [80 Gallon] [American Water Heater]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Water Heater%'
  AND ii.name_en ILIKE '%80 Gallon%'
  AND bv.brand ILIKE 'American Water Heater'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 2.0 Ton Rotary-R410A GREE]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 2.0 Ton Rotary-R410A GREE]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%2.0%'
  AND bv.brand ILIKE 'GREE'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 1.5 Ton Piston-R410A ORYX]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 1.5 Ton Piston-R410A ORYX]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Piston%'
  AND ii.name_en ILIKE '%1.5%'
  AND bv.brand ILIKE 'ORYX'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 3.0 Ton Rotary-R410A Hommer]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 3.0 Ton Rotary-R410A Hommer]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%3.0%'
  AND bv.brand ILIKE 'Hommer'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 3.0 Ton Rotary-R410A N&SYS]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 3.0 Ton Rotary-R410A N&SYS]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%3.0%'
  AND bv.brand ILIKE 'N&SYS'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 2.5 Ton Rotary-R410A N&SYS]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 2.5 Ton Rotary-R410A N&SYS]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%2.5%'
  AND bv.brand ILIKE 'N&SYS'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 1.5 Ton Rotary-R410A N&SYS]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 1.5 Ton Rotary-R410A N&SYS]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%1.5%'
  AND bv.brand ILIKE 'N&SYS'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 2.5 Ton Rotary-R410A ORYX]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 2.5 Ton Rotary-R410A ORYX]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%2.5%'
  AND bv.brand ILIKE 'ORYX'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 2.0 Ton Rotary-R410A ORYX]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 2.0 Ton Rotary-R410A ORYX]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%2.0%'
  AND bv.brand ILIKE 'ORYX'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 1.5 Ton Rotary-R410A ORYX]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 1.5 Ton Rotary-R410A ORYX]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%1.5%'
  AND bv.brand ILIKE 'ORYX'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 3.0 Ton Rotary-R410A Fergo]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 3.0 Ton Rotary-R410A Fergo]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%3.0%'
  AND bv.brand ILIKE 'Fergo'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 2.5 Ton Rotary-R410A Fergo]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 2.5 Ton Rotary-R410A Fergo]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%2.5%'
  AND bv.brand ILIKE 'Fergo'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 2.0 Ton Rotary-R410A Fergo]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 2.0 Ton Rotary-R410A Fergo]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%2.0%'
  AND bv.brand ILIKE 'Fergo'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 1.5 Ton Piston-R410A Fergo]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 1.5 Ton Piston-R410A Fergo]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Piston%'
  AND ii.name_en ILIKE '%1.5%'
  AND bv.brand ILIKE 'Fergo'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 2.0 Ton Rotary-R410A Hisense]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 2.0 Ton Rotary-R410A Hisense]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%2.0%'
  AND bv.brand ILIKE 'Hisense'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 1.5 Ton Rotary-R410A Hisense]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 1.5 Ton Rotary-R410A Hisense]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%1.5%'
  AND bv.brand ILIKE 'Hisense'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 3.0 Ton Rotary-R410A Midea]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 3.0 Ton Rotary-R410A Midea]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%3.0%'
  AND bv.brand ILIKE 'Midea'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 2.5 Ton Rotary-R410A Midea]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 2.5 Ton Rotary-R410A Midea]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%2.5%'
  AND bv.brand ILIKE 'Midea'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 2.0 Ton Rotary-R410A Midea]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 2.0 Ton Rotary-R410A Midea]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%2.0%'
  AND bv.brand ILIKE 'Midea'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 1.0 Ton Rotary-R410A Midea]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 1.0 Ton Rotary-R410A Midea]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%1.0%'
  AND bv.brand ILIKE 'Midea'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 2.0 Ton Inverter-R410A Midea]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 2.0 Ton Inverter-R410A Midea]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Inverter%'
  AND ii.name_en ILIKE '%2.0%'
  AND bv.brand ILIKE 'Midea'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 1.5 Ton Inverter-R410A Midea]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 1.5 Ton Inverter-R410A Midea]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Inverter%'
  AND ii.name_en ILIKE '%1.5%'
  AND bv.brand ILIKE 'Midea'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 3.0 Ton Piston-R410A Midea]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 3.0 Ton Piston-R410A Midea]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Piston%'
  AND ii.name_en ILIKE '%3.0%'
  AND bv.brand ILIKE 'Midea'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 2.7 Ton Piston-R410A Midea]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 2.7 Ton Piston-R410A Midea]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Piston%'
  AND ii.name_en ILIKE '%2.7%'
  AND bv.brand ILIKE 'Midea'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 1.7 Ton Piston-R410A Midea]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 1.7 Ton Piston-R410A Midea]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Piston%'
  AND ii.name_en ILIKE '%1.7%'
  AND bv.brand ILIKE 'Midea'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 1.0 Ton Rotary -R410A GREE]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 1.0 Ton Rotary -R410A GREE]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%1.0%'
  AND bv.brand ILIKE 'GREE'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 2.0 Ton Piston-R410A GREE]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 2.0 Ton Piston-R410A GREE]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Piston%'
  AND ii.name_en ILIKE '%2.0%'
  AND bv.brand ILIKE 'GREE'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 3.0 Ton Inverter-R410A GREE]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 3.0 Ton Inverter-R410A GREE]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Inverter%'
  AND ii.name_en ILIKE '%3.0%'
  AND bv.brand ILIKE 'GREE'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 2.5 Ton Inverter-R410A GREE]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 2.5 Ton Inverter-R410A GREE]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Inverter%'
  AND ii.name_en ILIKE '%2.5%'
  AND bv.brand ILIKE 'GREE'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 2.0 Ton Inverter-R410A GREE]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 2.0 Ton Inverter-R410A GREE]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Inverter%'
  AND ii.name_en ILIKE '%2.0%'
  AND bv.brand ILIKE 'GREE'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Split Type AC 1.5 Ton Inverter-R410A GREE]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Split Type AC 1.5 Ton Inverter-R410A GREE]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Split%'
  AND ic.name_en ILIKE '%Inverter%'
  AND ii.name_en ILIKE '%1.5%'
  AND bv.brand ILIKE 'GREE'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Window Type AC 2.0 Ton Rotary -R410A ORYX]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Window Type AC 2.0 Ton Rotary -R410A ORYX]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Window%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%2.0%'
  AND bv.brand ILIKE 'ORYX'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Window Type AC 2.0 Ton Rotary -R410A  Frego]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Window Type AC 2.0 Ton Rotary -R410A  Frego]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Window%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%2.0%'
  AND bv.brand ILIKE 'Frego'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Window Type AC 1.5 Ton Rotary -R410A  Frego]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Window Type AC 1.5 Ton Rotary -R410A  Frego]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Window%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%1.5%'
  AND bv.brand ILIKE 'Frego'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Window Type AC 2.0 Ton Rotary -R410A Hisense]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Window Type AC 2.0 Ton Rotary -R410A Hisense]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Window%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%2.0%'
  AND bv.brand ILIKE 'Hisense'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Window Type AC 1.5 Ton Rotary -R410A Hisense]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Window Type AC 1.5 Ton Rotary -R410A Hisense]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Window%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%1.5%'
  AND bv.brand ILIKE 'Hisense'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Window Type AC 2.0 Ton Rotary -R410A Midea]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Window Type AC 2.0 Ton Rotary -R410A Midea]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Window%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%2.0%'
  AND bv.brand ILIKE 'Midea'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Window Type AC 1.5 Ton Rotary -R410A Midea]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Window Type AC 1.5 Ton Rotary -R410A Midea]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Window%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%1.5%'
  AND bv.brand ILIKE 'Midea'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Window Type AC 2.0 Ton Rotary -R410A GREE]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Window Type AC 2.0 Ton Rotary -R410A GREE]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Window%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%2.0%'
  AND bv.brand ILIKE 'GREE'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Stand AC Type AC 3.0 Ton Rotary-R410A FREGO]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Stand AC Type AC 3.0 Ton Rotary-R410A FREGO]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Stand%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%3.0%'
  AND bv.brand ILIKE 'FREGO'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Stand AC Type AC 5.0 Ton Copeland-R410A FREGO]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Stand AC Type AC 5.0 Ton Copeland-R410A FREGO]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Stand%'
  AND ic.name_en ILIKE '%Copeland%'
  AND ii.name_en ILIKE '%5.0%'
  AND bv.brand ILIKE 'FREGO'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Stand AC Type AC 5.0 Ton Copeland-R410A Midea]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Stand AC Type AC 5.0 Ton Copeland-R410A Midea]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Stand%'
  AND ic.name_en ILIKE '%Copeland%'
  AND ii.name_en ILIKE '%5.0%'
  AND bv.brand ILIKE 'Midea'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Stand AC Type AC 4.0 Ton Copeland-R410A Midea]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Stand AC Type AC 4.0 Ton Copeland-R410A Midea]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Stand%'
  AND ic.name_en ILIKE '%Copeland%'
  AND ii.name_en ILIKE '%4.0%'
  AND bv.brand ILIKE 'Midea'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Stand AC Type AC 3.0 Ton Rotary-R410A Midea]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Stand AC Type AC 3.0 Ton Rotary-R410A Midea]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Stand%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%3.0%'
  AND bv.brand ILIKE 'Midea'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Stand AC Type AC 2.0 Ton Rotary-R410A Midea]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Stand AC Type AC 2.0 Ton Rotary-R410A Midea]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Stand%'
  AND ic.name_en ILIKE '%Rotary%'
  AND ii.name_en ILIKE '%2.0%'
  AND bv.brand ILIKE 'Midea'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Stand AC Type AC 5.0 Ton Copeland-R410A GREE]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Stand AC Type AC 5.0 Ton Copeland-R410A GREE]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Stand%'
  AND ic.name_en ILIKE '%Copeland%'
  AND ii.name_en ILIKE '%5.0%'
  AND bv.brand ILIKE 'GREE'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Stand AC Type AC 4.0 Ton Copeland-R410A GREE]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Stand AC Type AC 4.0 Ton Copeland-R410A GREE]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Stand%'
  AND ic.name_en ILIKE '%Copeland%'
  AND ii.name_en ILIKE '%4.0%'
  AND bv.brand ILIKE 'GREE'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Stand AC Type AC 8.0 Ton Inverter-R410A GREE]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Stand AC Type AC 8.0 Ton Inverter-R410A GREE]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Stand%'
  AND ic.name_en ILIKE '%Inverter%'
  AND ii.name_en ILIKE '%8.0%'
  AND bv.brand ILIKE 'GREE'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Floor Ceiling  AC Type AC 4.5 Ton Inverter-R410A GREE]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Floor Ceiling  AC Type AC 4.5 Ton Inverter-R410A GREE]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Floor Ceiling%'
  AND ic.name_en ILIKE '%Inverter%'
  AND ii.name_en ILIKE '%4.5%'
  AND bv.brand ILIKE 'GREE'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Floor Ceiling  AC Type AC 4.0 Ton Inverter-R410A GREE]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Floor Ceiling  AC Type AC 4.0 Ton Inverter-R410A GREE]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Floor Ceiling%'
  AND ic.name_en ILIKE '%Inverter%'
  AND ii.name_en ILIKE '%4.0%'
  AND bv.brand ILIKE 'GREE'
ON CONFLICT DO NOTHING;

-- Supply: Supply and Install[Floor Ceiling  AC Type AC 3.0 Ton Inverter-R410A GREE]
INSERT INTO service_inventory (id, service_id, brand_variant_id, link_type, quantity, is_default)
SELECT
  gen_random_uuid(),
  s.id,
  bv.id,
  'supply',
  1,
  TRUE
FROM services s
JOIN inventory_brand_variants bv ON TRUE
JOIN inventory_items ii ON bv.item_id = ii.id
JOIN inventory_categories ic ON ii.category_id = ic.id
WHERE s.name_en = 'Supply and Install[Floor Ceiling  AC Type AC 3.0 Ton Inverter-R410A GREE]'
  AND s.tree_type = 'normal'
  AND ic.name_en ILIKE '%Floor Ceiling%'
  AND ic.name_en ILIKE '%Inverter%'
  AND ii.name_en ILIKE '%3.0%'
  AND bv.brand ILIKE 'GREE'
ON CONFLICT DO NOTHING;
-- SKIP: Shower Filter

-- ============================================================
-- Part B: consumable reclassification
-- ============================================================

-- Consumable: Capacitor - Remove and install a new one [including capacitor cost]
UPDATE service_inventory
SET link_type = 'consumable'
WHERE service_id = (
  SELECT id FROM services
  WHERE name_en = 'Capacitor - Remove and install a new one [including capacitor cost]'
    AND tree_type = 'normal'
  LIMIT 1
);

-- Consumable: Contactor - Remove and install a new one [including contactor cost]
UPDATE service_inventory
SET link_type = 'consumable'
WHERE service_id = (
  SELECT id FROM services
  WHERE name_en = 'Contactor - Remove and install a new one [including contactor cost]'
    AND tree_type = 'normal'
  LIMIT 1
);

-- Consumable: Relay - Remove and install a new one [including relay cost]
UPDATE service_inventory
SET link_type = 'consumable'
WHERE service_id = (
  SELECT id FROM services
  WHERE name_en = 'Relay - Remove and install a new one [including relay cost]'
    AND tree_type = 'normal'
  LIMIT 1
);

-- Consumable: Fan capacitor -- Remove and install a new one [including fan capacitor cost]
UPDATE service_inventory
SET link_type = 'consumable'
WHERE service_id = (
  SELECT id FROM services
  WHERE name_en = 'Fan capacitor -- Remove and install a new one [including fan capacitor cost]'
    AND tree_type = 'normal'
  LIMIT 1
);

-- Consumable: Coil temperature sensor  - Remove and install a new one [including sensor cost]
UPDATE service_inventory
SET link_type = 'consumable'
WHERE service_id = (
  SELECT id FROM services
  WHERE name_en = 'Coil temperature sensor  - Remove and install a new one [including sensor cost]'
    AND tree_type = 'normal'
  LIMIT 1
);

-- Consumable: 3 Phase Contactor - Remove and install a new one [including contactor cost]
UPDATE service_inventory
SET link_type = 'consumable'
WHERE service_id = (
  SELECT id FROM services
  WHERE name_en = '3 Phase Contactor - Remove and install a new one [including contactor cost]'
    AND tree_type = 'normal'
  LIMIT 1
);

-- ============================================================
-- Part C: inventory_categories type update for consumables
-- ============================================================

UPDATE inventory_categories SET type = 'consumables'
WHERE name_en IN (
  'Electrical – Sockets & Switches',
  'Electrical – MCB & ELCB'
);

COMMIT;
