-- Seed country codes (GCC + common trading partners)
INSERT INTO public.country_codes (code, iso, flag, name, is_active, sort_order) VALUES
  ('+974', 'QA', '🇶🇦', 'Qatar',                true, 1),
  ('+966', 'SA', '🇸🇦', 'Saudi Arabia',          true, 2),
  ('+971', 'AE', '🇦🇪', 'United Arab Emirates',  true, 3),
  ('+973', 'BH', '🇧🇭', 'Bahrain',               true, 4),
  ('+968', 'OM', '🇴🇲', 'Oman',                   true, 5),
  ('+965', 'KW', '🇰🇼', 'Kuwait',                 true, 6),
  ('+91',  'IN', '🇮🇳', 'India',                  true, 10),
  ('+92',  'PK', '🇵🇰', 'Pakistan',               true, 11),
  ('+94',  'LK', '🇱🇰', 'Sri Lanka',              true, 12),
  ('+977', 'NP', '🇳🇵', 'Nepal',                  true, 13),
  ('+880', 'BD', '🇧🇩', 'Bangladesh',             true, 14),
  ('+63',  'PH', '🇵🇭', 'Philippines',            true, 15),
  ('+20',  'EG', '🇪🇬', 'Egypt',                  true, 20),
  ('+962', 'JO', '🇯🇴', 'Jordan',                 true, 21),
  ('+961', 'LB', '🇱🇧', 'Lebanon',                true, 22),
  ('+964', 'IQ', '🇮🇶', 'Iraq',                   true, 23),
  ('+90',  'TR', '🇹🇷', 'Turkey',                 true, 24),
  ('+98',  'IR', '🇮🇷', 'Iran',                   true, 25),
  ('+44',  'GB', '🇬🇧', 'United Kingdom',         true, 30),
  ('+1',   'US', '🇺🇸', 'United States',          true, 31),
  ('+86',  'CN', '🇨🇳', 'China',                  true, 32),
  ('+81',  'JP', '🇯🇵', 'Japan',                  true, 33),
  ('+82',  'KR', '🇰🇷', 'South Korea',            true, 34),
  ('+60',  'MY', '🇲🇾', 'Malaysia',               true, 35),
  ('+65',  'SG', '🇸🇬', 'Singapore',              true, 36),
  ('+62',  'ID', '🇮🇩', 'Indonesia',              true, 37),
  ('+49',  'DE', '🇩🇪', 'Germany',                true, 38),
  ('+33',  'FR', '🇫🇷', 'France',                 true, 39),
  ('+39',  'IT', '🇮🇹', 'Italy',                  true, 40),
  ('+27',  'ZA', '🇿🇦', 'South Africa',           true, 41),
  ('+254', 'KE', '🇰🇪', 'Kenya',                  true, 42),
  ('+234', 'NG', '🇳🇬', 'Nigeria',                true, 43),
  ('+55',  'BR', '🇧🇷', 'Brazil',                 true, 44)
ON CONFLICT DO NOTHING;

-- Seed currencies (GCC + major trading currencies)
INSERT INTO public.currencies (code, name, symbol, is_active, sort_order) VALUES
  ('QAR', 'Qatari Riyal',           'ر.ق',  true, 1),
  ('SAR', 'Saudi Riyal',            'ر.س',  true, 2),
  ('AED', 'UAE Dirham',             'د.إ',  true, 3),
  ('BHD', 'Bahraini Dinar',         '.د.ب', true, 4),
  ('OMR', 'Omani Rial',             'ر.ع',  true, 5),
  ('KWD', 'Kuwaiti Dinar',          'د.ك',  true, 6),
  ('USD', 'US Dollar',              '$',    true, 10),
  ('EUR', 'Euro',                   '€',    true, 11),
  ('GBP', 'British Pound',          '£',    true, 12),
  ('INR', 'Indian Rupee',           '₹',    true, 13),
  ('PKR', 'Pakistani Rupee',        'Rs',   true, 14),
  ('CNY', 'Chinese Yuan',           '¥',    true, 15),
  ('JPY', 'Japanese Yen',           '¥',    true, 16),
  ('KRW', 'South Korean Won',       '₩',    true, 17),
  ('TRY', 'Turkish Lira',           '₺',    true, 18),
  ('EGP', 'Egyptian Pound',         'E£',   true, 19),
  ('BDT', 'Bangladeshi Taka',       '৳',    true, 20),
  ('LKR', 'Sri Lankan Rupee',       'Rs',   true, 21),
  ('PHP', 'Philippine Peso',        '₱',    true, 22),
  ('MYR', 'Malaysian Ringgit',      'RM',   true, 23),
  ('SGD', 'Singapore Dollar',       'S$',   true, 24)
ON CONFLICT DO NOTHING;
