-- Add is_geocoded and waze_link columns to service_customer_addresses.
--
-- is_geocoded: tracks whether lat/lng were successfully resolved (hook already
--   writes this but the column was missing from the original CREATE TABLE).
-- waze_link:   stored Waze deep-link (https://waze.com/ul?ll=lat,lng&navigate=yes)
--   auto-generated by the app when coordinates are available; can also be manually set.

ALTER TABLE public.service_customer_addresses
  ADD COLUMN IF NOT EXISTS is_geocoded BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS waze_link   TEXT;

-- Back-fill is_geocoded for existing rows that already have coordinates
UPDATE public.service_customer_addresses
  SET is_geocoded = true
  WHERE lat IS NOT NULL AND lng IS NOT NULL AND is_geocoded = false;

-- Back-fill waze_link for existing rows that already have coordinates
UPDATE public.service_customer_addresses
  SET waze_link = 'https://waze.com/ul?ll=' || lat::text || ',' || lng::text || '&navigate=yes'
  WHERE lat IS NOT NULL AND lng IS NOT NULL AND waze_link IS NULL;
